#!/usr/bin/env python3
# The initial variant was generated by Google AI studio; modified manually later

import os
import pathlib
import importlib.util
import sys

# Traversing directories to some restricted depth.  Modified from
# https://stackoverflow.com/questions/7159607/list-directories-with-a-specified-depth-in-python
def _walk_dirs(path, depth):
    """Recursively list directories up to a certain depth"""
    depth -= 1
    with os.scandir(path) as p:
        for entry in p:
            if entry.is_dir():
                yield pathlib.Path(entry.path)
                if depth > 0:
                    yield from _walk_dirs(entry.path, depth)


def discover_working_dirs(root_path: str) -> list[pathlib.Path]:
    """
    Scans a project root directory for subdirectories until depth 2
    containing a 'config.py'.

    Args:
        root_path: The absolute path to the main project directory.

    Returns:
        A list of Path objects for each valid working directory found.

    """
    root = pathlib.Path(root_path)
    if not root.is_dir():
        print(f"Error: Project root '{root}' is not a valid directory.")
        return []

    found_dirs = []
    # os.scandir is more efficient than os.listdir for checking file types.
    for dir_ in _walk_dirs(root, 2):
        config_file = dir_ / "config.py"
        if config_file.is_file():
            found_dirs.append(dir_)
    return found_dirs


def find_matching_config(project_root: str, paths_to_check: [str]) -> dict | None:
    """
    Discovers working directories under a project root and checks their configs.

    It finds subdirectories with 'config.py', then safely loads each one
    to see if its 'font_dir' variable matches one of the 'paths_to_check'.

    Args:
        project_root: The path to the project root.
        paths_to_check: List of absolute paths to check for a match.

    Returns:
        The path to the first working directory that contains a matching config,
        or None if no match is found.
    """
    # Normalize the paths we are looking for to ensure consistent comparisons
    target_paths = [pathlib.Path(path).resolve() for path in paths_to_check]
    # Initialize the dictionary for results
    correspondence = {path: [] for path in target_paths}

    # 1. DISCOVERY PHASE
    working_dirs = discover_working_dirs(project_root)
    if not working_dirs:
        print(f"No subdirectories with a 'config.py' were found in '{project_root}'.")
        return None
    
    print(f"Found {len(working_dirs)} potential dirs to check...")
    print(", ".join([d.name for d in working_dirs]))
    print("-" * 20)

    # 2. CHECKING PHASE
    for wd_path in working_dirs:
        config_fname = wd_path / "config.py"
        spec = None  # Initialize spec to None for the cleanup in except block

        try:
            # Safely load the config.py file as a Python module
            spec = importlib.util.spec_from_file_location(
                name=f"config_{wd_path.name}",
                location=str(config_fname))
            config_module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = config_module
            spec.loader.exec_module(config_module)

            # Safely get the 'font_dir' attribute
            font_dir_val = getattr(config_module, 'font_dir', None)

            if font_dir_val:
                config_font_path = pathlib.Path(font_dir_val).resolve()
                for tpath in target_paths:
                    if config_font_path == tpath:
                        print(f"✅ Match found in: {wd_path}")
                        correspondence[tpath].append(str(wd_path))
            del sys.modules[spec.name]

        except Exception as e:
            print(f"❗️ Error processing {config_fname}: {e}")
        finally:
            # Ensure the temporary module is removed from the system cache
            if spec and spec.name in sys.modules:
                del sys.modules[spec.name]

    result = {str(p): l for p, l in correspondence.items() if l != []}
    if result == {}:
        return None
    else:
        return result

# --- How to Use It ---
if __name__ == "__main__":
    # 2. DEFINE THE PATHS YOU WANT TO FIND
    font_paths_to_check = []
    for i in range(1, len(sys.argv)):
        font_paths_to_check.append(sys.argv[i])
    print(f"Have {len(font_paths_to_check)} PFB dirs to check...")
    if len(font_paths_to_check) > 0:
        for d in font_paths_to_check:
            print(f"  - {str(d)}")
            print("-" * 20)

        # 1. DEFINE YOUR PROJECT ROOT
        project_root_directory = os.environ['project_dir']
        print(f"Searching under project root: '{project_root_directory}'")

        # 3. RUN THE CHECK
        matching_directories = find_matching_config(
            project_root=project_root_directory,
            paths_to_check=font_paths_to_check
        )

        if matching_directories:
            print(f"\n The found correspondence is {matching_directories}")
        else:
            print("❌ No matching configuration found in any discovered directory.")
    else:
        print(f"❌ No PFB files are found in the texlive tree.")
