#!/usr/bin/env python3
# The initial variant was generated by Google AI studio
from io_tex_data import read_tfm_list, generate_fonttable_tex_file
import sys
import os

pfb = sys.argv[1]
tex_file_name = os.path.join(os.environ['project_dir'], 'fonttable',
                             pfb + '.tex')
pfb_map_fname = os.path.join(os.environ['project_dir'],  'pfb-tfm-map.json')
tfm_list = read_tfm_list(pfb_map_fname, pfb + '.pfb')
generate_fonttable_tex_file(tfm_list,tex_file_name)
