#!/usr/bin/env python3
"""List glyphs that carry a variation selector on a base MathML does not call
stretchy -- the entries to reconsider if the tables are to conform.

A U+FE0x selector says "this is another SIZE cut of the same character", which
only means something for a character that expands.  MathML's operator
dictionary says which do (stretchy-chars.json).  Where a table applies a
selector to something outside that set, either the base is spelled differently
from the way MathML spells it, or the sequence says nothing at all.

The two cases are reported apart, because only the first is a rewrite:

  spelling   the base has a counterpart that IS stretchy -- almost always a
             combining mark whose spacing form MathML lists (U+0303 COMBINING
             TILDE vs U+02DC SMALL TILDE).  The pairing is Unicode's own
             compatibility decomposition, not a hand-made table.
  unlisted   no counterpart is stretchy: MathML has nothing to say about this
             character, so a selector on it is the table's own convention.

Usage:
  nonstretchy_variants.py --out FILE <table.lua> [<table.lua> ...]
"""
import argparse, os, re, sys, unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gpm_io as G

ap = argparse.ArgumentParser()
ap.add_argument("tables", nargs="+")
ap.add_argument("--data", default=G.DATA)
ap.add_argument("--out", required=True)
a = ap.parse_args()

stretchy = G.load_map("stretchy-chars.json", a.data)["chars"]

# Pair a spacing accent with its combining mark.  Unicode does it through the
# compatibility decomposition "<compat> 0020 XXXX" -- but only for some: SMALL
# TILDE and MACRON have one, while CARON and MODIFIER LETTER CIRCUMFLEX ACCENT
# have none at all.  So where that fails, the names are matched instead:
# a combining mark is named "COMBINING <X>" and its spacing form <X>, once the
# prefixes Unicode adds to the spacing name are taken off.
counterpart = {}
by_name = {}
for key in stretchy:
    cp = int(key[2:], 16)
    d = unicodedata.decomposition(chr(cp)).split()
    if len(d) == 3 and d[0] == "<compat>" and d[1] == "0020":
        counterpart[int(d[2], 16)] = cp
    try:
        nm = unicodedata.name(chr(cp))
    except ValueError:
        continue
    for prefix in ("MODIFIER LETTER ", "SMALL ", ""):
        if nm.startswith(prefix):
            by_name.setdefault(nm[len(prefix):], cp)

for cp in range(0x0300, 0x0370):
    if cp in counterpart:
        continue
    try:
        nm = unicodedata.name(chr(cp))
    except ValueError:
        continue
    if nm.startswith("COMBINING ") and nm[len("COMBINING "):] in by_name:
        counterpart[cp] = by_name[nm[len("COMBINING "):]]

ROW  = re.compile(r"""\[\s*['"]([^'"]+)['"]\s*\]\s*=\s*\{([^}]*)\}""")
HEXN = re.compile(r"0[xX]([0-9A-Fa-f]+)")

spelling, unlisted, ok = [], [], 0
for path in a.tables:
    try:
        text = open(path, encoding="utf-8").read()
    except OSError as e:
        print(f"  skipped {path}: {e}", file=sys.stderr)
        continue
    for m in ROW.finditer(text):
        name = m.group(1)
        codes = [int(h, 16) for h in HEXN.findall(m.group(2))]
        if not codes or not any(G.is_selector(c) for c in codes):
            continue
        base = codes[0]
        if f"U+{base:04X}" in stretchy:
            ok += 1
            continue
        try:
            nm = unicodedata.name(chr(base))
        except ValueError:
            nm = "?"
        sels = " ".join(f"U+{c:04X}" for c in codes if G.is_selector(c))
        alt = counterpart.get(base)
        row = (os.path.basename(path), name, base, nm, sels, alt)
        (spelling if alt else unlisted).append(row)

def block(title, rows, note):
    out = [f"{title}", "-" * len(title), note, ""]
    if not rows:
        out += ["  (none)", ""]
        return out
    w = max(len(r[1]) for r in rows)
    for f, name, base, nm, sels, alt in sorted(rows):
        line = f"  {f:24} {name:{w}}  U+{base:04X} {sels:12} {nm[:38]}"
        if alt:
            try: anm = unicodedata.name(chr(alt))
            except ValueError: anm = "?"
            line += f"\n  {'':24} {'':{w}}  -> U+{alt:04X} {anm[:44]}"
        out.append(line)
    out.append("")
    return out

lines = [
    "Glyphs whose variation sequence sits on a base MathML does not call",
    "stretchy.  Generated by pyscripts/nonstretchy_variants.py against",
    "stretchy-chars.json (MathML operator dictionary: stretchy | largeop).",
    "",
    f"Tables read: {len(a.tables)}",
    f"Sequences on a stretchy base (nothing to do): {ok}",
    f"To reconsider: {len(spelling)} spelling, {len(unlisted)} unlisted",
    "",
]
lines += block("SPELLING -- a counterpart of this base IS stretchy",
               spelling,
               "MathML lists the spacing accent, these tables use the combining\n"
               "mark.  Same accent, different spelling; the arrow is Unicode's own\n"
               "compatibility pairing.")
lines += block("UNLISTED -- no counterpart is stretchy either", unlisted,
               "MathML says nothing about these characters, so the selector here is\n"
               "this project's own convention rather than a conforming sequence.")
with open(a.out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"nonstretchy_variants: {len(spelling)} spelling + {len(unlisted)} unlisted "
      f"(of {ok + len(spelling) + len(unlisted)} sequences) -> {a.out}")
