#!/usr/bin/env python
# Need module PyMuPDF
# Script to find pdf chars without a suitable unicode.
# The function def initally was generated by gemini pro 2.5 b (Google AI Studio).
# The problem is that we sometime assign unicode 0xFFFD to unmappable characters.
import pymupdf  # PyMuPDF
import sys

def find_unmapped_characters(pdf_path: str, report_fname: str):
    """
    Scans a PDF for characters that could not be mapped to Unicode.
    This helps detect incomplete ToUnicode maps.
    """
    print(f"--- Scanning '{pdf_path}' for unmapped characters ---")
    found_issues = False
    doc = pymupdf.open(pdf_path)

    try:
        with open(report_fname, "w", encoding='utf-8') as report:
            for page_num, page in enumerate(doc, start=1):
                # Use the 'dict' format to get detailed info on every character
                text_dict = page.get_text("dict")
                for block in text_dict.get("blocks", []):
                    for line in block.get("lines", []):
                        for span in line.get("spans", []):
                            for char in span.get("chars", []):
                                # The Unicode Replacement Character signifies a decoding problem
                                if char["c"] == "\uFFFD":
                                    found_issues = True
                                    font = span["font"]
                                    bbox = pymupdf.Rect(char["bbox"])
                                    report.write(f"Page: {page_num}, bbox: {bbox.tl}, font: {font}.")
        doc.close()
        if not found_issues:
            print("[SUCCESS] No obvious unmapped characters found.")
        else:
            print("This PDF may have an incomplete ToUnicode map.")
    except IOError as e:
        print(f"Error: Could not write to file '{report_fname}': {e}")
        sys.exit(1)


if __name__ == "__main__":
    find_unmapped_characters(sys.argv[1],sys.argv[2])
