#!/usr/bin/env python 
# Generate maps from unicode names to MathMl 'mathvariant' values.
# Initial variant generated by Gemini 3.1 Pro Preview
import unicodedata
import json

# Define standard keywords for MathML variants
STYLE_KEYWORDS = {
    "DOUBLE-STRUCK": "double-struck",
    "SCRIPT": "script",
    "FRAKTUR": "fraktur",
    "BLACK-LETTER": "fraktur",
    "SANS-SERIF": "sans-serif",
    "MONOSPACE": "monospace",
    "BOLD": "bold",
    "ITALIC": "italic",
    "SMALL CAPITAL": "small-caps"
}

# Hand-verified overrides.  BASE_OVERRIDES corrects the unstyled base where the
# name-based resolver picks the wrong or unresolvable character; EXCLUDE drops
# historically-established symbols that are NOT a styled form of a base (so they
# stay as their own codepoint, never decomposed to base + mfont).
BASE_OVERRIDES = {
    0x1D03: "ƀ",   # LATIN LETTER SMALL CAPITAL BARRED B  -> b with stroke
    0x1D7B: "ɨ",   # LATIN SMALL CAPITAL I WITH STROKE     -> i with stroke
    0x1D7E: "ʉ",   # LATIN SMALL CAPITAL U WITH STROKE     -> u with stroke
}
EXCLUDE_CODEPOINTS = {
    0x2118,        # SCRIPT CAPITAL P (Weierstrass p): a symbol, not a styled 'P'
    # No plain counterpart exists ("LATIN SMALL LETTER R WITH RIGHT LEG" is not
    # a character), so the base resolver fell through to the character itself
    # and recorded it as a small-caps form OF ITSELF.
    0xAB46,        # LATIN LETTER SMALL CAPITAL R WITH RIGHT LEG
    # The letterlike script l.  U+1D4C1 MATHEMATICAL SCRIPT SMALL L is the
    # systematic encoding of 'l' + script; this one is the legacy symbol, and
    # keeping both made them contend for base 'l' + script.
    0x2113,        # SCRIPT SMALL L
}
# Recorded with a variant but kept as their own codepoint (base = the char
# itself, so the finder treats them as keep-as-base, never base+mfont).
# The double-struck italic set (ⅅ ⅆ ⅇ ⅈ ⅉ) used to be here, because MathML has
# no 'double-struck-italic' mathvariant.  They are now decomposed like any other
# styled character -- the record states what the font really holds, and the
# MathML restrictions are for a later transformation step to resolve.
KEEP_AS_BASE_CODEPOINTS = set()

# Helper function to determine standard MathML-like variants
def get_mathvariant(props):
    """Return the variant as an ordered LIST of atomic property tokens.

    Each element is itself a valid token (may contain a hyphen, e.g.
    'sans-serif', 'double-struck'), so the list stays unambiguously
    splittable; the MathML mathvariant value is '-'.join(list) (e.g.
    ['sans-serif','bold','italic'] -> 'sans-serif-bold-italic').  The list
    order is the canonical MathML order, not sorted order.
    """
    props_tuple = tuple(sorted(set(props)))
    mapping = {
        ("bold",): ["bold"],
        ("italic",): ["italic"],
        ("bold", "italic"): ["bold", "italic"],
        ("double-struck",): ["double-struck"],
        ("fraktur",): ["fraktur"],
        ("bold", "fraktur"): ["bold", "fraktur"],
        ("script",): ["script"],
        ("bold", "script"): ["bold", "script"],
        ("sans-serif",): ["sans-serif"],
        ("bold", "sans-serif"): ["bold", "sans-serif"],
        ("italic", "sans-serif"): ["sans-serif", "italic"],
        ("bold", "italic", "sans-serif"): ["sans-serif", "bold", "italic"],
        ("monospace",): ["monospace"],
        ("small-caps",): ["small-caps"],
        ("bold", "small-caps"): ["bold", "small-caps"],
    }
    if props_tuple in mapping:
        return mapping[props_tuple]
    return list(props_tuple)

# Helper function to find the unstyled base character
def resolve_base_char(char, name):
    """Attempt to find the unstyled base character for a styled Unicode character."""
    # 1. ONE decomposition step -- not NFKD.
    # NFKD is transitive, and it flattened every Greek SYMBOL form to the plain
    # letter: U+1D717 MATHEMATICAL ITALIC THETA SYMBOL -> U+03D1 GREEK THETA
    # SYMBOL -> U+03B8 GREEK SMALL LETTER THETA.  So the symbol form and the
    # letter form came out with the same base AND the same properties, 35 pairs
    # of them, and each pair then had to fight over one slot in
    # base_to_variants.  Unicode gives the symbol shapes their own codepoints
    # precisely so they can be told apart; stopping after one step keeps them:
    # U+1D717 -> ϑ, U+1D703 -> θ, and the collision does not arise.
    d = unicodedata.decomposition(char)
    if d:
        parts = [p for p in d.split() if not p.startswith("<")]
        if parts:
            return "".join(chr(int(p, 16)) for p in parts)

    # 2. Base resolution for "WHITE" (double-struck) brackets/parentheses
    ## removed
        
    # 3. Base resolution for gothic
    if "BLACK-LETTER" in name or "FRAKTUR" in name:
        base_name = name.replace("MATHEMATICAL ", "") \
                        .replace("BLACK-LETTER ", "") \
                        .replace("FRAKTUR ", "") \
                        .replace("  ", " ").strip()
        try:
            return unicodedata.lookup(base_name)
        except KeyError:
            pass
    
    # 4. Base resolution for SMALL CAPITALS
    if "SMALL CAPITAL" in name:
        letter_name = name.split("SMALL CAPITAL ")[-1].strip()
        prefixes = ["LATIN SMALL LETTER ", "GREEK SMALL LETTER ", "CYRILLIC SMALL LETTER "]
        for prefix in prefixes:
            try:
                return unicodedata.lookup(prefix + letter_name)
            except KeyError:
                continue
        if len(letter_name) == 1:
            return letter_name.lower()
        if letter_name == "AE": return "æ"
        if letter_name == "OE": return "œ"
        
    # 5. Base resolution for undecomposed standalone Letterlike symbols
    # (Captures isolated mathematical symbols like "SCRIPT CAPITAL P" and "SCRIPT SMALL L")
    parts = name.split()
    if "CAPITAL" in parts or "SMALL" in parts:
        last_word = parts[-1]
        if len(last_word) == 1 and last_word.isalpha():
            if "SMALL" in parts and "SMALL CAPITAL" not in name:
                return last_word.lower()
            return last_word.upper()
            
    return char

# Two characters can claim the same base+variant key
# Preference, in order:
#   1. the plain letter over the SYMBOL form   -- fixes all 35 Greek cases
#   2. the Mathematical Alphanumeric Symbols block over legacy/letterlike
#   3. the lower codepoint, as the older and more canonical assignment
# Rule 3 gives U+27E6 (Miscellaneous Mathematical Symbols-A) over U+301A (CJK
# punctuation), which is the one a maths font means.
def base_name(ch):
    """The Unicode name, or a readable placeholder for the unnamed."""
    try:
        return unicodedata.name(ch)
    except ValueError:
        return f"(unnamed U+{ord(ch):04X})"

MATH_ALNUM = range(0x1D400, 0x1D800)
PREFER_OVERRIDE = {}        # (base, token) -> chosen char, for what the rules miss
collisions = []

def prefer(a, b, base=None, token=None):
    """Which of two characters claiming one base+variant key to keep."""
    hand = PREFER_OVERRIDE.get((base, token))
    if hand in (a, b):
        return hand
    def score(ch):
        name = unicodedata.name(ch)
        return ("SYMBOL" in name,                 # False sorts first: letter wins
                ord(ch) not in MATH_ALNUM,        # False first: math block wins
                ord(ch))                          # then the lower codepoint
    return min((a, b), key=score)

def extract_math_and_font_variants():
    """Main extraction routine to parse Unicode and generate JSON mappings."""
    char_to_props = {}
    base_to_variants = {}

    # Main Processing Loop
    for codepoint in range(0x110000):
        char = chr(codepoint)
        try:
            name = unicodedata.name(char)
        except ValueError:
            continue

        if codepoint in EXCLUDE_CODEPOINTS:
            continue

        # CLEANING: Exclude phonetic modifiers and Arabic mathematical text
        if "MODIFIER" in name or "COMBINING" in name or "ARABIC" in name or \
           "TURNED" in name or "INVERTED" in name or "REVERSED" in name or \
           "PRESCRIPTION" in name:
            continue
            
        # Identify applied font properties
        props = []
        for kw, variant_val in STYLE_KEYWORDS.items():
            if kw in name:
                props.append(variant_val)
                
        if not props:
            continue
            
        # Filter for mathematical blocks, letter-like, small caps, and our specific additions
        is_math = "MATHEMATICAL" in name
        is_letterlike = 0x2100 <= codepoint <= 0x214F
        is_small_cap = "SMALL CAPITAL" in name
        is_blackletter_or_fraktur = "BLACK-LETTER" in name or "FRAKTUR" in name
        
        if not (is_math or is_letterlike or is_small_cap or is_blackletter_or_fraktur):
            continue
            
        mathvariant = get_mathvariant(props)
        if codepoint in KEEP_AS_BASE_CODEPOINTS:
            base_char = char
        else:
            base_char = BASE_OVERRIDES.get(codepoint, resolve_base_char(char, name))
        
        # Populate mapping dictionaries
        char_to_props[char] = {
            "codepoint": f"U+{codepoint:04X}",
            "name": name,
            "base": base_char,
            # The base spelled out as well as shown.  The character alone is hard
            # to read in a diff and impossible to grep for: 'base': 'ꭆ' says
            # nothing, 'basecode': 'U+AB46' with the same value as this entry's
            # own codepoint says at once that the entry claims to be a styled
            # form of itself.  Every base is a single named character (checked),
            # so both fields are single-valued.
            "basecode": " ".join(f"U+{ord(c):04X}" for c in base_char),
            "basename": " + ".join(base_name(c) for c in base_char),
            "mathvariant": mathvariant
        }
        
        if base_char not in base_to_variants:
            base_to_variants[base_char] = {}
        # key by the MathML token ('-'.join of the ordered property list)
        key = "-".join(mathvariant)
        rival = base_to_variants[base_char].get(key)
        if rival is None:
            base_to_variants[base_char][key] = char
        else:
            win = prefer(rival, char, base_char, key)
            collisions.append((base_char, key, rival, char, win))
            base_to_variants[base_char][key] = win

    # Export mapping outputs
    with open("char_to_properties.json", "w", encoding="utf-8") as f:
        json.dump(char_to_props, f, ensure_ascii=False, indent=2)
        
    with open("base_to_variants.json", "w", encoding="utf-8") as f:
        json.dump(base_to_variants, f, ensure_ascii=False, indent=2)

    if collisions:
        print(f"\n{len(collisions)} base+variant key(s) claimed by two characters "
              f"-- one had to be chosen (see prefer(), PREFER_OVERRIDE to force):")
        for base, key, a, b, win in collisions:
            lose = b if win == a else a
            print(f"  {base!r} + {key}: kept U+{ord(win):04X} "
                  f"{unicodedata.name(win)}  (over U+{ord(lose):04X} "
                  f"{unicodedata.name(lose)})")
    print(f"\nExtraction complete: Processed {len(char_to_props)} clean, stylized characters.")
    print("Exported mappings to 'char_to_properties.json' and 'base_to_variants.json'.")

if __name__ == "__main__":
    extract_math_and_font_variants()
