  ['bbsum'] = { 0x2140, }, --⅀ Double-Struck N-Ary Summation
  ['bigcap'] = { 0x22C2, }, --⋂ N-Ary Intersection
  ['bigcup'] = { 0x22C3, }, --⋃ N-Ary Union
  ['bigcupdot'] = { 0x2A03, }, --⨃ N-Ary Union Operator with Dot
  ['bigcupplus'] = { 0x2A04, }, --⨄ N-Ary Union Operator with Plus
  ['bigdblland'] = { 0x2A07, }, --⨇ Two Logical and Operator
  ['bigdbllor'] = { 0x2A08, }, --⨈ Two Logical or Operator
  ['bigland'] = { 0x22C0, }, --⋀ N-Ary Logical And
  ['biglor'] = { 0x22C1, }, --⋁ N-Ary Logical Or
  ['bigodot'] = { 0x2A00, }, --⨀ N-Ary Circled Dot Operator
  ['bigoplus'] = { 0x2A01, }, --⨁ N-Ary Circled Plus Operator
  ['bigotimes'] = { 0x2A02, }, --⨂ N-Ary Circled Times Operator
  ['bigsqcap'] = { 0x2A05, }, --⨅ N-Ary Square Intersection Operator
  ['bigsqcup'] = { 0x2A06, }, --⨆ N-Ary Square Union Operator
  ['bigtimes'] = { 0x2A09, }, --⨉ N-Ary Times Operator
  ['coproduct'] = { 0x2210, }, --∐ N-Ary Coproduct
  ['coproduct'] = { 0x2A3F, }, --⨿ Amalgamation or Coproduct
  ['intcap'] = { 0x2A19, }, --⨙ Integral with Intersection
  ['intcontour'] = { 0x222E, }, --∮ Contour Integral
  ['intcup'] = { 0x2A1A, }, --⨚ Integral with Union
  ['intdbl'] = { 0x222C, }, --∬ Double Integral
  ['intdblstroke'] = { 0x2A0E, }, --⨎ Integral with Double Stroke
  ['integral'] = { 0x222B, }, --∫ Integral
  ['integralbt'] = { 0x2321, }, --⌡ Bottom Half Integral
  ['integralex'] = { 0x23AE, }, --⎮ Integral Extension
  ['integraltp'] = { 0x2320, }, --⌠ Top Half Integral
  ['intfinpart'] = { 0x2A0D, }, --⨍ Finite Part Integral
  ['intleftarrhook'] = { 0x2A17, }, --⨗ Integral with Leftwards Arrow with Hook
  ['intleftcontour'] = { 0x2233, }, --∳ Anticlockwise Contour Integral
  ['intodot'] = { 0x2A15, }, --⨕ Integral Around A Point Operator
  ['intoverbar'] = { 0x2A1B, }, --⨛ Integral with Overbar
  ['intquadr'] = { 0x2A0C, }, --⨌ Quadruple Integral Operator
  ['intquater'] = { 0x2A16, }, --⨖ Quaternion Integral Operator
  ['intrightcontour'] = { 0x2232, }, --∲ Clockwise Contour Integral
  ['intrightdir'] = { 0x2231, }, --∱ Clockwise Integral
  ['intslash'] = { 0x2A0F, }, --⨏ Integral Average with Slash
  ['intsurf'] = { 0x222F, }, --∯ Surface Integral
  ['inttimes'] = { 0x2A18, }, --⨘ Integral with Times Sign
  ['inttriple'] = { 0x222D, }, --∭ Triple Integral
  ['intunderbar'] = { 0x2A1C, }, --⨜ Integral with Underbar
  ['intvol'] = { 0x2230, }, --∰ Volume Integral
  ['product'] = { 0x220F, }, --∏ N-Ary Product
  ['sumintegral'] = { 0x2A0B, }, --⨋ Summation with Integral
  ['summation'] = { 0x2211, }, --∑ N-Ary Summation
  ['summationbt'] = { 0x23B3, }, --⎳ Summation Bottom
  ['summationtp'] = { 0x23B2, }, --⎲ Summation Top
  ['summodtwo'] = { 0x2A0A, }, --⨊ Modulo Two Sum
  ['vertbarop'] = { 0x2AFF, }, --⫿ N-Ary White Vertical Bar
