  ['Alpha'] = { 0x0391 }, --Α Greek Capital Letter Alpha
  ['Beta'] = { 0x0392 }, --Β Greek Capital Letter Beta
  ['Chi'] = { 0x03A7 }, --Χ Greek Capital Letter Chi
  ['Delta'] = { 0x0394 }, --Δ Greek Capital Letter Delta
  ['Epsilon'] = { 0x0395 }, --Ε Greek Capital Letter Epsilon
  ['Eta'] = { 0x0397 }, --Η Greek Capital Letter Eta
  ['Gamma'] = { 0x0393 }, --Γ Greek Capital Letter Gamma
  ['Iota'] = { 0x0399 }, --Ι Greek Capital Letter Iota
  ['Kappa'] = { 0x039A }, --Κ Greek Capital Letter Kappa
  ['Koppa'] = { 0x03DE }, --Ϟ Greek Letter Koppa
  ['Lambda'] = { 0x039B }, --Λ Greek Capital Letter Lamda
  ['Mu'] = { 0x039C }, --Μ Greek Capital Letter Mu
  ['Nu'] = { 0x039D }, --Ν Greek Capital Letter Nu
  ['Omega'] = { 0x03A9 }, --Ω Greek Capital Letter Omega
  ['Omicron'] = { 0x039F }, --Ο Greek Capital Letter Omicron
  ['Phi'] = { 0x03A6 }, --Φ Greek Capital Letter Phi
  ['Pi'] = { 0x03A0 }, --Π Greek Capital Letter Pi
  ['Psi'] = { 0x03A8 }, --Ψ Greek Capital Letter Psi
  ['Rho'] = { 0x03A1 }, --Ρ Greek Capital Letter Rho
  ['Sigma'] = { 0x03A3 }, --Σ Greek Capital Letter Sigma
  ['Stigma'] = { 0x03DA }, --Ϛ Greek Letter Stigma
  ['Tau'] = { 0x03A4 }, --Τ Greek Capital Letter Tau
  ['Theta'] = { 0x0398 }, --Θ Greek Capital Letter Theta
  ['Upsilon'] = { 0x03A5 }, --Υ Greek Capital Letter Upsilon
  ['Xi'] = { 0x039E }, --Ξ Greek Capital Letter Xi
  ['Zeta'] = { 0x0396 }, --Ζ Greek Capital Letter Zeta
  ['Alphatonos'] = { 0x0386 }, --Ά Greek Capital Letter Alpha with Tonos
  ['Digamma'] = { 0x03DC }, --Ϝ Greek Letter Digamma
  ['Digammapamphylian'] = { 0x0376 }, --Ͷ Greek Capital Letter Pamphylian Digamma
  ['Epsilontonos'] = { 0x0388 }, --Έ Greek Capital Letter Epsilon with Tonos
  ['Etatonos'] = { 0x0389 }, --Ή Greek Capital Letter Eta with Tonos
  ['Heta'] = { 0x0370 }, --Ͱ Greek Capital Letter Heta
  ['Iotadialytika'] = { 0x03AA }, --Ϊ Greek Capital Letter Iota with Dialytika
  ['Iotatonos'] = { 0x038A }, --Ί Greek Capital Letter Iota with Tonos
  ['Kai'] = { 0x03CF }, --Ϗ Greek Capital Kai Symbol
  ['Kai'] = { 0x03D7 }, --ϗ Greek Kai Symbol
  ['Koppaarchaic'] = { 0x03D8 }, --Ϙ Greek Letter Archaic Koppa
  ['Omegatonos'] = { 0x038F }, --Ώ Greek Capital Letter Omega with Tonos
  ['Omicrontonos'] = { 0x038C }, --Ό Greek Capital Letter Omicron with Tonos
  ['Sampi'] = { 0x03E0 }, --Ϡ Greek Letter Sampi
  ['Sampiarchaic'] = { 0x0372 }, --Ͳ Greek Capital Letter Archaic Sampi
  ['San'] = { 0x03FA }, --Ϻ Greek Capital Letter San
  ['Sho'] = { 0x03F7 }, --Ϸ Greek Capital Letter Sho
  ['Sigmalunate'] = { 0x03F9 }, --Ϲ Greek Capital Lunate Sigma Symbol
  ['Sigmalunatedotted'] = { 0x03FE }, --Ͼ Greek Capital Dotted Lunate Sigma Symbol
  ['Sigmalunatereversed'] = { 0x03FD }, --Ͻ Greek Capital Reversed Lunate Sigma Symbol
  ['Sigmalunatereverseddotted'] = { 0x03FF }, --Ͽ Greek Capital Reversed Dotted Lunate Sigma Symbol
  ['Theta1'] = { 0x03F4 }, --ϴ Greek Capital Theta Symbol
  ['Upsilonacutehook'] = { 0x03D3 }, --ϓ Greek Upsilon with Acute and Hook Symbol
  ['Upsilondiaeresishook'] = { 0x03D4 }, --ϔ Greek Upsilon with Diaeresis and Hook Symbol
  ['Upsilondialytika'] = { 0x03AB }, --Ϋ Greek Capital Letter Upsilon with Dialytika
  ['Upsilonhook'] = { 0x03D2 }, --ϒ Greek Upsilon with Hook Symbol
  ['Upsilontonos'] = { 0x038E }, --Ύ Greek Capital Letter Upsilon with Tonos
  ['Yot'] = { 0x037F }, --Ϳ Greek Capital Letter Yot
  ['alpha'] = { 0x03B1 }, --α Greek Small Letter Alpha
  ['beta'] = { 0x03B2 }, --β Greek Small Letter Beta
  ['chi'] = { 0x03C7 }, --χ Greek Small Letter Chi
  ['delta'] = { 0x03B4 }, --δ Greek Small Letter Delta
  ['epsilon'] = { 0x03B5 }, --ε Greek Small Letter Epsilon
  ['epsilon1'] = { 0x03F5 }, --ϵ Greek Lunate Epsilon Symbol
  ['eta'] = { 0x03B7 }, --η Greek Small Letter Eta
  ['gamma'] = { 0x03B3 }, --γ Greek Small Letter Gamma
  ['iota'] = { 0x03B9 }, --ι Greek Small Letter Iota
  ['kappa'] = { 0x03BA }, --κ Greek Small Letter Kappa
  ['kappa1'] = { 0x03F0 }, --ϰ Greek Kappa Symbol
  ['lambda'] = { 0x03BB }, --λ Greek Small Letter Lamda
  ['mu'] = { 0x03BC }, --μ Greek Small Letter Mu
  ['nu'] = { 0x03BD }, --ν Greek Small Letter Nu
  ['omega'] = { 0x03C9 }, --ω Greek Small Letter Omega
  ['omicron'] = { 0x03BF }, --ο Greek Small Letter Omicron
  ['phi'] = { 0x03C6 }, --φ Greek Small Letter Phi
  ['phi1'] = { 0x03D5 }, --ϕ Greek Phi Symbol
  ['pi'] = { 0x03C0 }, --π Greek Small Letter Pi
  ['pi1'] = { 0x03D6 }, --ϖ Greek Pi Symbol
  ['psi'] = { 0x03C8 }, --ψ Greek Small Letter Psi
  ['rho'] = { 0x03C1 }, --ρ Greek Small Letter Rho
  ['rho1'] = { 0x03F1 }, --ϱ Greek Rho Symbol
  ['sigma'] = { 0x03C3 }, --σ Greek Small Letter Sigma
  ['sigma1'] = { 0x03C2 }, --ς Greek Small Letter Final Sigma
  ['stigma'] = { 0x03DB }, --ϛ Greek Small Letter Stigma
  ['tau'] = { 0x03C4 }, --τ Greek Small Letter Tau
  ['theta'] = { 0x03B8 }, --θ Greek Small Letter Theta
  ['theta1'] = { 0x03D1 }, --ϑ Greek Theta Symbol
  ['upsilon'] = { 0x03C5 }, --υ Greek Small Letter Upsilon
  ['xi'] = { 0x03BE }, --ξ Greek Small Letter Xi
  ['zeta'] = { 0x03B6 }, --ζ Greek Small Letter Zeta
  ['alphatonos'] = { 0x03AC }, --ά Greek Small Letter Alpha with Tonos
  ['anoteleia'] = { 0x0387 }, --· Greek Ano Teleia
  ['beta1'] = { 0x03D0 }, --ϐ Greek Beta Symbol
  ['dialytikatonos'] = { 0x0385 }, --΅ Greek Dialytika Tonos
  ['digamma'] = { 0x03DD }, --ϝ Greek Small Letter Digamma
  ['digammapamphylian'] = { 0x0377 }, --ͷ Greek Small Letter Pamphylian Digamma
  ['epsilonreversed'] = { 0x03F6 }, --϶ Greek Reversed Lunate Epsilon Symbol
  ['epsilontonos'] = { 0x03AD }, --έ Greek Small Letter Epsilon with Tonos
  ['etatonos'] = { 0x03AE }, --ή Greek Small Letter Eta with Tonos
  ['heta'] = { 0x0371 }, --ͱ Greek Small Letter Heta
  ['iotadialytika'] = { 0x03CA }, --ϊ Greek Small Letter Iota with Dialytika
  ['iotadialytikatonos'] = { 0x0390 }, --ΐ Greek Small Letter Iota with Dialytika and Tonos
  ['iotatonos'] = { 0x03AF }, --ί Greek Small Letter Iota with Tonos
  ['koppa'] = { 0x03DF }, --ϟ Greek Small Letter Koppa
  ['koppaArchaic'] = { 0x03D9 }, --ϙ Greek Small Letter Archaic Koppa
  ['numeralsign'] = { 0x0374 }, --ʹ Greek Numeral Sign
  ['numeralsignlower'] = { 0x0375 }, --͵ Greek Lower Numeral Sign
  ['omegatonos'] = { 0x03CE }, --ώ Greek Small Letter Omega with Tonos
  ['omicrontonos'] = { 0x03CC }, --ό Greek Small Letter Omicron with Tonos
  ['questionmark'] = { 0x037E }, --; Greek Question Mark
  ['rhostroke'] = { 0x03FC }, --ϼ Greek Rho with Stroke Symbol
  ['sampi'] = { 0x03E1 }, --ϡ Greek Small Letter Sampi
  ['sampiarchaic'] = { 0x0373 }, --ͳ Greek Small Letter Archaic Sampi
  ['san'] = { 0x03FB }, --ϻ Greek Small Letter San
  ['sho'] = { 0x03F8 }, --ϸ Greek Small Letter Sho
  ['sigmalunate'] = { 0x03F2 }, --ϲ Greek Lunate Sigma Symbol
  ['sigmalunatedotted'] = { 0x037C }, --ͼ Greek Small Dotted Lunate Sigma Symbol
  ['sigmalunatereversed'] = { 0x037B }, --ͻ Greek Small Reversed Lunate Sigma Symbol
  ['sigmalunatereverseddotted'] = { 0x037D }, --ͽ Greek Small Reversed Dotted Lunate Sigma Symbol
  ['tonos'] = { 0x0384 }, --΄ Greek Tonos
  ['upsilondialytika'] = { 0x03CB }, --ϋ Greek Small Letter Upsilon with Dialytika
  ['upsilondialytikatonos'] = { 0x03B0 }, --ΰ Greek Small Letter Upsilon with Dialytika and Tonos
  ['upsilontonos'] = { 0x03CD }, --ύ Greek Small Letter Upsilon with Tonos
  ['yot'] = { 0x03F3 }, --ϳ Greek Letter Yot
  ['ypogegrammeni'] = { 0x037A }, --ͺ Greek Ypogegrammeni
  ['Dei'] = { 0x03EE }, --Ϯ Coptic Capital Letter Dei
  ['Fei'] = { 0x03E4 }, --Ϥ Coptic Capital Letter Fei
  ['Gangia'] = { 0x03EA }, --Ϫ Coptic Capital Letter Gangia
  ['Hori'] = { 0x03E8 }, --Ϩ Coptic Capital Letter Hori
  ['Khei'] = { 0x03E6 }, --Ϧ Coptic Capital Letter Khei
  ['Shei'] = { 0x03E2 }, --Ϣ Coptic Capital Letter Shei
  ['Shima'] = { 0x03EC }, --Ϭ Coptic Capital Letter Shima
  ['dei'] = { 0x03EF }, --ϯ Coptic Small Letter Dei
  ['fei'] = { 0x03E5 }, --ϥ Coptic Small Letter Fei
  ['gangia'] = { 0x03EB }, --ϫ Coptic Small Letter Gangia
  ['hori'] = { 0x03E9 }, --ϩ Coptic Small Letter Hori
  ['khei'] = { 0x03E7 }, --ϧ Coptic Small Letter Khei
  ['shei'] = { 0x03E3 }, --ϣ Coptic Small Letter Shei
  ['shima'] = { 0x03ED }, --ϭ Coptic Small Letter Shima
