  ['zero.inferior'] = { 0x2080, 'zerosubscript' },-- SUBSCRIPT ZERO
  ['one.inferior'] = { 0x2081, 'onesubscript' },-- SUBSCRIPT ONE
  ['two.inferior'] = { 0x2082, 'twosubscript' },-- SUBSCRIPT TWO
  ['three.inferior'] = { 0x2083, 'threesubscript' },-- SUBSCRIPT THREE
  ['four.inferior'] = { 0x2084, 'foursubscript' },-- SUBSCRIPT FOUR
  ['five.inferior'] = { 0x2085, 'fivesubscript' },-- SUBSCRIPT FIVE
  ['six.inferior'] = { 0x2086, 'sixsubscript' },-- SUBSCRIPT SIX
  ['seven.inferior'] = { 0x2087, 'sevensubscript' },-- SUBSCRIPT SEVEN
  ['eight.inferior'] = { 0x2088, 'eightsubscript' },-- SUBSCRIPT EIGHT
  ['nine.inferior'] = { 0x2089, 'ninesubscript' },-- SUBSCRIPT NINE
  ['plus.inferior'] = { 0x208A, 'plussubscript' },-- SUBSCRIPT PLUS SIGN
  ['minus.inferior'] = { 0x208B, 'minussubscript' },-- SUBSCRIPT MINUS
  ['equal.inferior'] = { 0x208C, 'equalsubscript' },-- SUBSCRIPT EQUALS SIGN
  ['parenleft.inferior'] = { 0x208D, 'parenleftsubscript' },-- SUBSCRIPT LEFT PARENTHESIS
  ['parenright.inferior'] = { 0x208E, 'parenrightsubscript' },-- SUBSCRIPT RIGHT PARENTHESIS
  ['a.inferior'] = { 0x2090, 'asubscript' },-- LATIN SUBSCRIPT SMALL LETTER A
  ['e.inferior'] = { 0x2091, 'esubscript' },-- LATIN SUBSCRIPT SMALL LETTER E
  ['h.inferior'] = { 0x2095, 'hsubscript' },-- LATIN SUBSCRIPT SMALL LETTER H
  ['i.inferior'] = { 0x1D62, 'isubscript' },-- LATIN SUBSCRIPT SMALL LETTER I
  ['j.inferior'] = { 0x2C7C, 'jsubscript' },-- LATIN SUBSCRIPT SMALL LETTER J
  ['k.inferior'] = { 0x2096, 'ksubscript' },-- LATIN SUBSCRIPT SMALL LETTER K
  ['l.inferior'] = { 0x2097, 'lsubscript' },-- LATIN SUBSCRIPT SMALL LETTER L
  ['m.inferior'] = { 0x2098, 'msubscript' },-- LATIN SUBSCRIPT SMALL LETTER M
  ['n.inferior'] = { 0x2099, 'nsubscript' },-- LATIN SUBSCRIPT SMALL LETTER N
  ['o.inferior'] = { 0x2092, 'osubscript' },-- LATIN SUBSCRIPT SMALL LETTER O
  ['p.inferior'] = { 0x209A, 'psubscript' },-- LATIN SUBSCRIPT SMALL LETTER P
  ['r.inferior'] = { 0x1D63, 'rsubscript' },-- LATIN SUBSCRIPT SMALL LETTER R
  ['s.inferior'] = { 0x209B, 'ssubscript' },-- LATIN SUBSCRIPT SMALL LETTER S
  ['t.inferior'] = { 0x209C, 'tsubscript' },-- LATIN SUBSCRIPT SMALL LETTER T
  ['u.inferior'] = { 0x1D64, 'usubscript' },-- LATIN SUBSCRIPT SMALL LETTER U
  ['v.inferior'] = { 0x1D65, 'vsubscript' },-- LATIN SUBSCRIPT SMALL LETTER V
  ['x.inferior'] = { 0x2093, 'xsubscript' },-- LATIN SUBSCRIPT SMALL LETTER X
  ['schwa.inferior'] = { 0x2094, 'schwasubscript' },--ₔ Latin Subscript Small Letter Schwa
  ['beta.inferior'] = { 0x1D66, 'betasubscript' },--ᵦ Greek Subscript Small Letter Beta
  ['gamma.inferior'] = { 0x1D67, 'gammasubscript' },--ᵧ Greek Subscript Small Letter Gamma
  ['rho.inferior'] = { 0x1D68, 'rhosubscript' },--ᵨ Greek Subscript Small Letter Rho
  ['chi.inferior'] = { 0x1D6A, 'chisubscript' },--ᵪ Greek Subscript Small Letter Chi
  ['acyr.inferior'] = { 0x1E051, },--𞁑 Cyrillic Subscript Small Letter A
  ['becyr.inferior'] = { 0x1E052, },--𞁒 Cyrillic Subscript Small Letter Be
  ['vecyr.inferior'] = { 0x1E053, },--𞁓 Cyrillic Subscript Small Letter Ve
  ['ghecyr.inferior'] = { 0x1E054, },--𞁔 Cyrillic Subscript Small Letter Ghe
  ['decyr.inferior'] = { 0x1E055, },--𞁕 Cyrillic Subscript Small Letter De
  ['iecyr.inferior'] = { 0x1E056, },--𞁖 Cyrillic Subscript Small Letter Ie
  ['zhecyr.inferior'] = { 0x1E057, },--𞁗 Cyrillic Subscript Small Letter Zhe
  ['zecyr.inferior'] = { 0x1E058, },--𞁘 Cyrillic Subscript Small Letter Ze
  ['icyr.inferior'] = { 0x1E059, },--𞁙 Cyrillic Subscript Small Letter I
  ['kacyr.inferior'] = { 0x1E05A, },--𞁚 Cyrillic Subscript Small Letter Ka
  ['elcyr.inferior'] = { 0x1E05B, },--𞁛 Cyrillic Subscript Small Letter El
  ['ocyr.inferior'] = { 0x1E05C, },--𞁜 Cyrillic Subscript Small Letter O
  ['pecyr.inferior'] = { 0x1E05D, },--𞁝 Cyrillic Subscript Small Letter Pe
  ['escyr.inferior'] = { 0x1E05E, },--𞁞 Cyrillic Subscript Small Letter Es
  ['ucyr.inferior'] = { 0x1E05F, },--𞁟 Cyrillic Subscript Small Letter U
  ['efcyr.inferior'] = { 0x1E060, },--𞁠 Cyrillic Subscript Small Letter Ef
  ['hacyr.inferior'] = { 0x1E061, },--𞁡 Cyrillic Subscript Small Letter Ha
  ['tsecyr.inferior'] = { 0x1E062, },--𞁢 Cyrillic Subscript Small Letter Tse
  ['checyr.inferior'] = { 0x1E063, },--𞁣 Cyrillic Subscript Small Letter Che
  ['shacyr.inferior'] = { 0x1E064, },--𞁤 Cyrillic Subscript Small Letter Sha
  ['hardsigncyr.inferior'] = { 0x1E065, },--𞁥 Cyrillic Subscript Small Letter Hard Sign
  ['yerucyr.inferior'] = { 0x1E066, },--𞁦 Cyrillic Subscript Small Letter Yeru
  ['gheupturncyr.inferior'] = { 0x1E067, },--𞁧 Cyrillic Subscript Small Letter Ghe With Upturn
  ['Ibelukrcyr.inferior'] = { 0x1E068, },--𞁨 Cyrillic Subscript Small Letter Byelorussian-Ukrainian I
  ['dzecyr.inferior'] = { 0x1E069, },--𞁩 Cyrillic Subscript Small Letter Dze
  ['dzhecyr.inferior'] = { 0x1E06A, },--𞁪 Cyrillic Subscript Small Letter Dzhe
