  ['Bbarredsmall'] = { 0x1D03, }, --ᴃ: Latin Letter Small Capital Barred B
  ['Eturnedsmall'] = { 0x2C7B, }, --ⱻ: Latin Letter Small Capital Turned E
  ['Gammasmall'] = { 0x1D26, }, --ᴦ: Greek Letter Small Capital Gamma
  ['Ghooksmall'] = { 0x029B, }, --ʛ: Latin Letter Small Capital G with Hook
  ['Ismallnot'] = { 0xA7AE, }, --Ɪ: Latin Capital Letter Small Capital I
  ['Istrokesmall'] = { 0x1D7B, }, --ᵻ: Latin Letter Small Capital I with Stroke
  ['Lamdasmall'] = { 0x1D27, }, --ᴧ: Greek Letter Small Capital Lamda
  ['Lstrokesmall'] = { 0x1D0C, }, --ᴌ: Latin Letter Small Capital L with Stroke
  ['Mturnedsmall'] = { 0xA7FA, }, --ꟺ: Latin Letter Small Capital Turned M
  ['Nreversedsmall'] = { 0x1D0E, }, --ᴎ: Latin Letter Small Capital Reversed N
  ['Omegasmall'] = { 0xAB65, }, --ꭥ: Greek Letter Small Capital Omega
  ['Oopensmall'] = { 0x1D10, }, --ᴐ: Latin Letter Small Capital Open O
  ['Pismall'] = { 0x1D28, }, --ᴨ: Greek Letter Small Capital Pi
  ['Psismall'] = { 0x1D2A, }, --ᴪ: Greek Letter Small Capital Psi
  ['Rhosmall'] = { 0x1D29, }, --ᴩ: Greek Letter Small Capital Rho
  ['Rinvertedsmall'] = { 0x0281, }, --ʁ: Latin Letter Small Capital Inverted R
  ['Rlonglegsmall'] = { 0xAB46, }, --ꭆ: Latin Letter Small Capital R with Right Leg
  ['Rreversedsmall'] = { 0x1D19, }, --ᴙ: Latin Letter Small Capital Reversed R
  ['Rsmallcap'] = { 0x0280, },-- LATIN LETTER SMALL CAPITAL R
  ['Rturnedsmall'] = { 0x1D1A, }, --ᴚ: Latin Letter Small Capital Turned R
  ['Rumsmall'] = { 0xA776, }, --ꝶ: Latin Letter Small Capital Rum
  ['Ustrokesmall'] = { 0x1D7E, }, --ᵾ: Latin Letter Small Capital U with Stroke
  ['a.sc'] = { 0x1D00, 'aSC' },-- LATIN LETTER SMALL CAPITAL A
  ['b.sc'] = { 0x0299, 'bSC' },-- LATIN LETTER SMALL CAPITAL B
  ['c.sc'] = { 0x1D04, 'cSC' },-- LATIN LETTER SMALL CAPITAL C
  ['d.sc'] = { 0x1D05, 'dSC' },-- LATIN LETTER SMALL CAPITAL D
  ['e.sc'] = { 0x1D07, 'eSC' },-- LATIN LETTER SMALL CAPITAL E
  ['f.sc'] = { 0xA730, 'fSC' },-- LATIN LETTER SMALL CAPITAL F
  ['g.sc'] = { 0x0262, 'gSC' },-- LATIN LETTER SMALL CAPITAL G
  ['h.sc'] = { 0x029C, 'hSC' },-- LATIN LETTER SMALL CAPITAL H
  ['i.sc'] = { 0x026A, 'iSC' },-- LATIN LETTER SMALL CAPITAL I
  ['j.sc'] = { 0x1D0A, 'jSC' },-- LATIN LETTER SMALL CAPITAL J
  ['k.sc'] = { 0x1D0B, 'kSC' },-- LATIN LETTER SMALL CAPITAL K
  ['l.sc'] = { 0x029F, 'lSC' },-- LATIN LETTER SMALL CAPITAL L
  ['m.sc'] = { 0x1D0D, 'mSC' },-- LATIN LETTER SMALL CAPITAL M
  ['n.sc'] = { 0x0274, 'nSC' },-- LATIN LETTER SMALL CAPITAL N
  ['o.sc'] = { 0x1D0F, 'oSC' },-- LATIN LETTER SMALL CAPITAL O
  ['p.sc'] = { 0x1D18, 'pSC' },-- LATIN LETTER SMALL CAPITAL P
  ['q.sc'] = { 0xA7AF, 'qSC' },-- LATIN LETTER SMALL CAPITAL Q
  ['r.sc'] = { 0x0280, 'rSC' },-- LATIN LETTER SMALL CAPITAL R
  ['s.sc'] = { 0xA731, 'sSC' },-- LATIN LETTER SMALL CAPITAL S
  ['t.sc'] = { 0x1D1B, 'tSC' },-- LATIN LETTER SMALL CAPITAL T
  ['u.sc'] = { 0x1D1C, 'uSC' },-- LATIN LETTER SMALL CAPITAL U
  ['v.sc'] = { 0x1D20, 'vSC' },-- LATIN LETTER SMALL CAPITAL V
  ['w.sc'] = { 0x1D21, 'wSC' },-- LATIN LETTER SMALL CAPITAL W
  ['y.sc'] = { 0x028F, 'ySC' },-- LATIN LETTER SMALL CAPITAL Y
  ['z.sc'] = { 0x1D22, 'zSC' },-- LATIN LETTER SMALL CAPITAL Z
  ['aacute.sc'] = { 0x1D00, 0x0301, 'AacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING ACUTE ACCENT
  ['abreve.sc'] = { 0x1D00, 0x0306, 'AbreveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE
  ['abreveacute.sc'] = { 0x1D00, 0x0306, 0x0301, 'AbreveacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING ACUTE ACCENT
  ['abrevedotbelow.sc'] = { 0x1D00, 0x0306, 0x0323, 'AbrevedotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING DOT BELOW
  ['abrevegrave.sc'] = { 0x1D00, 0x0306, 0x0300, 'AbrevegraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING GRAVE ACCENT
  ['abrevehookabove.sc'] = { 0x1D00, 0x0306, 0x0309, 'AbrevehookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING HOOK ABOVE
  ['abrevetilde.sc'] = { 0x1D00, 0x0306, 0x0303, 'AbrevetildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING TILDE
  ['acaron.sc'] = { 0x1D00, 0x030C, 'AcaronSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CARON
  ['acircumflex.sc'] = { 0x1D00, 0x0302, 'AcircumflexSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT
  ['acircumflexacute.sc'] = { 0x1D00, 0x0302, 0x0301, 'AcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['acircumflexdotbelow.sc'] = { 0x1D00, 0x0302, 0x0323, 'AcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['acircumflexgrave.sc'] = { 0x1D00, 0x0302, 0x0300, 'AcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['acircumflexhookabove.sc'] = { 0x1D00, 0x0302, 0x0309, 'AcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['acircumflextilde.sc'] = { 0x1D00, 0x0302, 0x0303, 'AcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['adblgrave.sc'] = { 0x1D00, 0x030F, 'AdblgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOUBLE GRAVE ACCENT
  ['adieresis.sc'] = { 0x1D00, 0x0308, 'AdieresisSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DIAERESIS
  ['adotbelow.sc'] = { 0x1D00, 0x0323, 'AdotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOT BELOW
  ['ae.sc'] = { 0x1D01, 'AESC' },-- LATIN LETTER SMALL CAPITAL AE
  ['aeacute.sc'] = { 0x1D01, 0x0301, 'AEacuteSC' },-- LATIN LETTER SMALL CAPITAL AE/COMBINING ACUTE ACCENT
  ['agrave.sc'] = { 0x1D00, 0x0300, 'AgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING GRAVE ACCENT
  ['ahookabove.sc'] = { 0x1D00, 0x0309, 'AhookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING HOOK ABOVE
  ['amacron.sc'] = { 0x1D00, 0x0304, 'AmacronSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING MACRON
  ['aogonek.sc'] = { 0x1D00, 0x0328, 'AogonekSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK
  ['aogonekacute.sc'] = { 0x1D00, 0x0328, 0x0301, 'AogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['aring.sc'] = { 0x1D00, 0x030A, 'AringSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE
  ['aringacute.sc'] = { 0x1D00, 0x030A, 0x0301, 'AringacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE/COMBINING ACUTE ACCENT
  ['atilde.sc'] = { 0x1D00, 0x0303, 'AtildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING TILDE
  ['cacute.sc'] = { 0x1D04, 0x0301, 'CacuteSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING ACUTE ACCENT
  ['ccaron.sc'] = { 0x1D04, 0x030C, 'CcaronSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CARON
  ['ccedilla.sc'] = { 0x1D04, 0x0327, 'CcedillaSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CEDILLA
  ['ccircumflex.sc'] = { 0x1D04, 0x0302, 'CcircumflexSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CIRCUMFLEX ACCENT
  ['cdotaccent.sc'] = { 0x1D04, 0x0307, 'CdotaccentSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING DOT ABOVE
  ['dcaron.sc'] = { 0x1D05, 0x030C, 'DcaronSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING CARON
  ['dcroat.sc'] = { 0x1D06, 'DcroatSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING SHORT STROKE OVERLAY
  ['ddotbelow.sc'] = { 0x1D05, 0x0323, 'DdotbelowSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING DOT BELOW
  ['dlinebelow.sc'] = { 0x1D05, 0x0331, 'DlinebelowSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING MACRON BELOW
  ['dotlessi.sc'] = { 0x026A, 'IdotlesSC' },-- LATIN LETTER SMALL CAPITAL I
  ['dotlessj.sc'] = { 0x1D0A, 'JdotlessSC' },-- LATIN LETTER SMALL CAPITAL J
  ['eacute.sc'] = { 0x1D07, 0x0301, 'EacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING ACUTE ACCENT
  ['ebreve.sc'] = { 0x1D07, 0x0306, 'EbreveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING BREVE
  ['ecaron.sc'] = { 0x1D07, 0x030C, 'EcaronSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CARON
  ['ecircumflex.sc'] = { 0x1D07, 0x0302, 'EcircumflexSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT
  ['ecircumflexacute.sc'] = { 0x1D07, 0x0302, 0x0301, 'EcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ecircumflexdotbelow.sc'] = { 0x1D07, 0x0302, 0x0323, 'EcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ecircumflexgrave.sc'] = { 0x1D07, 0x0302, 0x0300, 'EcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ecircumflexhookabove.sc'] = { 0x1D07, 0x0302, 0x0309, 'EcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ecircumflextilde.sc'] = { 0x1D07, 0x0302, 0x0303, 'EcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['edblgrave.sc'] = { 0x1D07, 0x030F, 'EdblgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOUBLE GRAVE ACCENT
  ['edieresis.sc'] = { 0x1D07, 0x0308, 'EdieresisSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DIAERESIS
  ['edotaccent.sc'] = { 0x1D07, 0x0307, 'EdotaccentSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT ABOVE
  ['edotbelow.sc'] = { 0x1D07, 0x0323, 'EdotbelowSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT BELOW
  ['egrave.sc'] = { 0x1D07, 0x0300, 'EgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING GRAVE ACCENT
  ['el'] = { 0x1D2B, }, --ᴫ: Cyrillic Letter Small Capital El
  ['ehookabove.sc'] = { 0x1D07, 0x0309, 'EhookaboveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING HOOK ABOVE
  ['emacron.sc'] = { 0x1D07, 0x0304, 'EmacronSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING MACRON
  ['eogonek.sc'] = { 0x1D07, 0x0328, 'EogonekSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK
  ['eogonekacute.sc'] = { 0x1D07, 0x0328, 0x0301, 'EogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['ereversed.sc'] = { 0x2C7B, 'EreversedSC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['eth.sc'] = { 0x1D06, 'ethSC' },-- LATIN LETTER SMALL CAPITAL ETH
  ['etilde.sc'] = { 0x1D07, 0x0303, 'EtildeSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING TILDE
  ['eturned.sc'] = { 0x2C7B, 'EturnedSC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['ezh.sc'] = { 0x1D23, 'ezhSC' }, --ᴣ: Latin Letter Small Capital Ezh
  ['gacute.sc'] = { 0x0262, 0x0301, 'GacuteSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING ACUTE ACCENT
  ['gbreve.sc'] = { 0x0262, 0x0306, 'GbreveSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING BREVE
  ['gcaron.sc'] = { 0x0262, 0x030C, 'GcaronSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CARON
  ['gcircumflex.sc'] = { 0x0262, 0x0302, 'GcircumflexSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CIRCUMFLEX ACCENT
  ['gcommaaccent.sc'] = { 0x0262, 0x0326, 'GSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING COMMA BELOW
  ['gdotaccent.sc'] = { 0x0262, 0x0307, 'GdotaccentSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING DOT ABOVE
  ['germandbls.scalt'] = { 0xA731, 0xA731, 'germandblsSCalt' },-- LATIN LETTER SMALL CAPITAL S/LATIN LETTER SMALL CAPITAL S
  ['hbar.sc'] = { 0x029C, 0x0336, 'HbarSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING LONG STROKE OVERLAY
  ['hbrevebelow.sc'] = { 0x029C, 0x032E, 'HbrevebelowSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING BREVE BELOW
  ['hcircumflex.sc'] = { 0x029C, 0x0302, 'HcircumflexSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING CIRCUMFLEX ACCENT
  ['hdieresis.sc'] = { 0x029C, 0x0308, 'HdieresisSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DIAERESIS
  ['hdotbelow.sc'] = { 0x029C, 0x0323, 'HdotbelowSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DOT BELOW
  ['iacute.sc'] = { 0x026A, 0x0301, 'IacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING ACUTE ACCENT
  ['ibreve.sc'] = { 0x026A, 0x0306, 'IbreveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING BREVE
  ['icaron.sc'] = { 0x026A, 0x030C, 'IcaronSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CARON
  ['icircumflex.sc'] = { 0x026A, 0x0302, 'IcircumflexSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CIRCUMFLEX ACCENT
  ['idblgrave.sc'] = { 0x026A, 0x030F, 'IdblgraveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOUBLE GRAVE ACCENT
  ['idieresis.sc'] = { 0x026A, 0x0308, 'IdieresisSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS
  ['idieresisacute.sc'] = { 0x026A, 0x0308, 0x0301, 'IdieresisacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['idotaccent.sc'] = { 0x026A, 0x0307, 'IdotaccentSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT ABOVE
  ['idotbelow.sc'] = { 0x026A, 0x0323, 'IdotbelowSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT BELOW
  ['igrave.sc'] = { 0x026A, 0x0300, 'IgraveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING GRAVE ACCENT
  ['ihookabove.sc'] = { 0x026A, 0x0309, 'IhookaboveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING HOOK ABOVE
  ['ij.sc'] = { 0x026A, 0x1D0A, 'ijSC' },-- LATIN LETTER SMALL CAPITAL I/LATIN LETTER SMALL CAPITAL J
  ['imacron.alt.sc'] = { 0x026A, 0x0304, 'ImacronaltSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['imacron.sc'] = { 0x026A, 0x0304, 'ImacronSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['iogonek.sc'] = { 0x026A, 0x0328, 'IogonekSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK
  ['iogonekacute.sc'] = { 0x026A, 0x0328, 0x0301, 'IogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['itilde.sc'] = { 0x026A, 0x0303, 'ItildeSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING TILDE
  ['jacute.sc'] = { 0x1D0A, 0x0301, 'JacuteSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING ACUTE ACCENT
  ['jcaron.sc'] = { 0x1D0A, 0x030C, 'JcaronSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CARON
  ['jcircumflex.sc'] = { 0x1D0A, 0x0302, 'JcircumflexSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CIRCUMFLEX ACCENT
  ['kcommaaccent.sc'] = { 0x1D0B, 0x0326, 'KcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL K/COMBINING COMMA BELOW
  ['lacute.sc'] = { 0x029F, 0x0301, 'LacuteSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING ACUTE ACCENT
  ['lcaron.sc'] = { 0x029F, 0x0315, 'LcaronSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA ABOVE RIGHT
  ['lcommaaccent.sc'] = { 0x029F, 0x0326, 'LcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA BELOW
  ['ldot.sc'] = { 0x029F, 0x0358, 'LdotSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT ABOVE RIGHT
  ['ldotbelow.sc'] = { 0x029F, 0x0323, 'LdotbelowSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW
  ['ldotbelowmacron.sc'] = { 0x029F, 0x0323, 0x0304, 'LdotbelowmacronSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW/COMBINING MACRON
  ['lslash.sc'] = { 0x1D0C, 'LslashSC' },-- LATIN LETTER SMALL CAPITAL L WITH STROKE
  ['mdotbelow.sc'] = { 0x1D0D, 0x0323, 'MdotbelowSC' },-- LATIN LETTER SMALL CAPITAL M/COMBINING DOT BELOW
  ['nacute.sc'] = { 0x0274, 0x0301, 'NacuteSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING ACUTE ACCENT
  ['ncaron.sc'] = { 0x0274, 0x030C, 'NcaronSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING CARON
  ['ncommaaccent.sc'] = { 0x0274, 0x0326, 'NcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING COMMA BELOW
  ['ndotaccent.sc'] = { 0x0274, 0x0307, 'NdotaccentSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT ABOVE
  ['ndotbelow.sc'] = { 0x0274, 0x0323, 'NdotbelowSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT BELOW
  ['ntilde.sc'] = { 0x0274, 0x0303, 'NtildeSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING TILDE
  ['oacute.sc'] = { 0x1D0F, 0x0301, 'OacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING ACUTE ACCENT
  ['obreve.sc'] = { 0x1D0F, 0x0306, 'ObreveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING BREVE
  ['ocircumflex.sc'] = { 0x1D0F, 0x0302, 'OcircumflexSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT
  ['ocircumflexacute.sc'] = { 0x1D0F, 0x0302, 0x0301, 'OcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ocircumflexdotbelow.sc'] = { 0x1D0F, 0x0302, 0x0323, 'OcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ocircumflexgrave.sc'] = { 0x1D0F, 0x0302, 0x0300, 'OcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ocircumflexhookabove.sc'] = { 0x1D0F, 0x0302, 0x0309, 'OcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ocircumflextilde.sc'] = { 0x1D0F, 0x0302, 0x0303, 'OcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['odblgrave.sc'] = { 0x1D0F, 0x030F, 'OdblgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE GRAVE ACCENT
  ['odieresis.sc'] = { 0x1D0F, 0x0308, 'OdieresisSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DIAERESIS
  ['odotbelow.sc'] = { 0x1D0F, 0x0323, 'OdotbelowSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOT BELOW
  ['oe.sc'] = { 0x0276, 'OESC' },-- LATIN LETTER SMALL CAPITAL OE
  ['ograve.sc'] = { 0x1D0F, 0x0300, 'OgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING GRAVE ACCENT
  ['ohookabove.sc'] = { 0x1D0F, 0x0309, 'OhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HOOK ABOVE
  ['ohorn.sc'] = { 0x1D0F, 0x031B, 'OhornSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohornacute.sc'] = { 0x1D0F, 0x031B, 0x0301, 'OhornacuteSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohorndotbelow.sc'] = { 0x1D0F, 0x031B, 0x0323,  'OhorndotbelowSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohorngrave.sc'] = { 0x1D0F, 0x031B, 0x0300, 'OhorngraveSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohornhookabove.sc'] = { 0x1D0F, 0x031B, 0x0309, 'OhornhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohorntilde.sc'] = { 0x1D0F, 0x031B, 0x0303, 'OhorntildeSC' },-- LATIN LETTER SMALL CAPITAL O
  ['ohungarumlaut.sc'] = { 0x1D0F, 0x030B, 'OhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE ACUTE ACCENT
  ['omacron.sc'] = { 0x1D0F, 0x0304, 'OmacronSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING MACRON
  ['oogonek.sc'] = { 0x1D0F, 0x0328, 'OogonekSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK
  ['oogonekacute.sc'] = { 0x1D0F, 0x0328, 0x0301, 'OogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['otilde.sc'] = { 0x1D0F, 0x0303, 'OtildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING TILDE
  ['ou'] = { 0x1D15, }, --ᴕ: Latin Letter Small Capital Ou
  ['racute.sc'] = { 0x0280, 0x0301, 'RacuteSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING ACUTE ACCENT
  ['rcaron.sc'] = { 0x0280, 0x030C, 'RcaronSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING CARON
  ['rcommaaccent.sc'] = { 0x0280, 0x0326, 'RcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING COMMA BELOW
  ['rdblgrave.sc'] = { 0x0280, 0x030F, 'RdblgraveSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOUBLE GRAVE ACCENT
  ['rdotaccent.sc'] = { 0x0280, 0x0307, 'RdotaccentSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT ABOVE
  ['rdotbelow.sc'] = { 0x0280, 0x0323, 'RdotbelowSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW
  ['rdotbelowmacron.sc'] = { 0x0280, 0x0323, 0x0304, 'RdotbelowmacronSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW/COMBINING MACRON
  ['sacute.sc'] = { 0xA731, 0x0301, 'SacuteSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING ACUTE ACCENT
  ['scaron.sc'] = { 0xA731, 0x030C, 'ScaronSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CARON
  ['scedilla.sc'] = { 0xA731, 0x0327, 'ScedillaSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CEDILLA
  ['scircumflex.sc'] = { 0xA731, 0x0302, 'ScircumflexSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CIRCUMFLEX ACCENT
  ['scommaaccent.sc'] = { 0xA731, 0x0326, 'ScommaaccentSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING COMMA BELOW
  ['sdotbelow.sc'] = { 0xA731, 0x0323, 'SdotbelowSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING DOT BELOW
  ['tbar.sc'] = { 0x1D1B, 0x0335, 'TbarSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING SHORT STROKE OVERLAY
  ['tcaron.sc'] = { 0x1D1B, 0x030C, 'TcaronSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CARON
  ['tcedilla.sc'] = { 0x1D1B, 0x0327, 'TcedillaSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CEDILLA
  ['tdieresis.sc'] = { 0x1D1B, 0x0308, 'TdieresisSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DIAERESIS
  ['tdotbelow.sc'] = { 0x1D1B, 0x0323, 'TdotbelowSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DOT BELOW
  ['tlinebelow.sc'] = { 0x1D1B, 0x0331, 'TlinebelowSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING MACRON BELOW
  ['uacute.sc'] = { 0x1D1C, 0x0301, 'UacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING ACUTE ACCENT
  ['ubreve.sc'] = { 0x1D1C, 0x0306, 'UbreveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING BREVE
  ['ubrevebelowinverted.sc'] = { 0x1D1C, 0x032F, 'UbrevebelowinvertedSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING INVERTED BREVE BELOW
  ['ucaron.sc'] = { 0x1D1C, 0x030C, 'UcaronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CARON
  ['ucircumflex.sc'] = { 0x1D1C, 0x0302, 'UcircumflexSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CIRCUMFLEX ACCENT
  ['udblgrave.sc'] = { 0x1D1C, 0x030F, 'UdblgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE GRAVE ACCENT
  ['udieresis.sc'] = { 0x1D1C, 0x0308, 'UdieresisSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS
  ['udieresisacute.sc'] = { 0x1D1C, 0x0308, 0x0301, 'UdieresisacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['udieresiscaron.sc'] = { 0x1D1C, 0x0308, 0x030C, 'UdieresiscaronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING CARON
  ['udieresisgrave.sc'] = { 0x1D1C, 0x0308, 0x0300, 'UdieresisgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING GRAVE ACCENT
  ['udotbelow.sc'] = { 0x1D1C, 0x0323, 'UdotbelowSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOT BELOW
  ['ugrave.sc'] = { 0x1D1C, 0x0300, 'UgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING GRAVE ACCENT
  ['uhookabove.sc'] = { 0x1D1C, 0x0309, 'UhookaboveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HOOK ABOVE
  ['uhorn.sc'] = { 0x1D1C, 0x031B, 'UhornSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN
  ['uhornacute.sc'] = { 0x1D1C, 0x031B, 0x0301, 'UhornacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING ACUTE ACCENT
  ['uhorndotbelow.sc'] = { 0x1D1C, 0x031B, 0x0323,  'UhorndotbelowSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING DOT BELOW
  ['uhorngrave.sc'] = { 0x1D1C, 0x031B, 0x0300, 'UhorngraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING GRAVE ACCENT
  ['uhornhookabove.sc'] = { 0x1D1C, 0x031B, 0x0309, 'UhornhookaboveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING HOOK ABOVE
  ['uhorntilde.sc'] = { 0x1D1C, 0x031B, 0x0303, 'UhorntildeSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING TILDE
  ['uhungarumlaut.sc'] = { 0x1D1C, 0x030B, 'UhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE ACUTE ACCENT
  ['umacron.sc'] = { 0x1D1C, 0x0304, 'UmacronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING MACRON
  ['uogonek.sc'] = { 0x1D1C, 0x0328, 'UogonekSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING OGONEK
  ['uring.sc'] = { 0x1D1C, 0x030A, 'UringSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING RING ABOVE
  ['utilde.sc'] = { 0x1D1C, 0x0303, 'UtildeSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING TILDE
  ['wacute.sc'] = { 0x1D21, 0x0301, 'WacuteSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING ACUTE ACCENT
  ['wcircumflex.sc'] = { 0x1D21, 0x0302, 'WcircumflexSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING CIRCUMFLEX ACCENT
  ['wdieresis.sc'] = { 0x1D21, 0x0308, 'WdieresisSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING DIAERESIS
  ['wgrave.sc'] = { 0x1D21, 0x0300, 'WgraveSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING GRAVE ACCENT
  ['yacute.sc'] = { 0x028F, 0x0301, 'YacuteSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING ACUTE ACCENT
  ['ycircumflex.sc'] = { 0x028F, 0x0302, 'YcircumflexSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING CIRCUMFLEX ACCENT
  ['ydieresis.sc'] = { 0x028F, 0x0308, 'YdieresisSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DIAERESIS
  ['ydotbelow.sc'] = { 0x028F, 0x0323, 'YdotbelowSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DOT BELOW
  ['ygrave.sc'] = { 0x028F, 0x0300, 'YgraveSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING GRAVE ACCENT
  ['yhookabove.sc'] = { 0x028F, 0x0309, 'YhookaboveSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING HOOK ABOVE
  ['ytilde.sc'] = { 0x028F, 0x0303, 'YtildeSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING TILDE
  ['zacute.sc'] = { 0x1D22, 0x0301, 'ZacuteSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING ACUTE ACCENT
  ['zcaron.sc'] = { 0x1D22, 0x030C, 'ZcaronSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING CARON
  ['zdotaccent.sc'] = { 0x1D22, 0x0307, 'ZdotaccentSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT ABOVE
  ['zdotbelow.sc'] = { 0x1D22, 0x0323, 'ZdotbelowSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT BELOW

  ['exclam.pc'] = { 0xFE57, 'exclamPC' },-- SMALL EXCLAMATION MARK
  ['numbersign.pc'] = { 0xFE5F, 'numbersignPC' },-- SMALL NUMBER SIGN
  ['dollar.pc'] = { 0xFE69, 'dollarPC' },-- SMALL DOLLAR SIGN
  ['percent.pc'] = { 0xFE6A, 'percentPC' },-- SMALL PERCENT SIGN
  ['ampersand.pc'] = { 0xFE60, 'ampersandPC' },-- SMALL AMPERSAND
  ['parenleft.pc'] = { 0xFE59, 'parenleftPC' },-- SMALL LEFT PARENTHESIS
  ['parenright.pc'] = { 0xFE5A, 'parenrightPC' },-- SMALL RIGHT PARENTHESIS
  ['asterisk.pc'] = { 0xFE61, 'asteriskPC' },-- SMALL ASTERISK
  ['plus.pc'] = { 0xFE62, 'plusPC' },-- SMALL PLUS SIGN
  ['comma.pc'] = { 0xFE50, 'commaPC' },-- SMALL COMMA
  ['hyphen.pc'] = { 0xFE63, 'hyphenPC' },-- SMALL HYPHEN-MINUS
  ['period.pc'] = { 0xFE52, 'periodPC' },-- SMALL FULL STOP
  ['slash.pc'] = { 0xFE68, 'slashPC' },-- SMALL REVERSE SOLIDUS
  ['colon.pc'] = { 0xFE55, 'colonPC' },-- SMALL COLON
  ['semicolon.pc'] = { 0xFE54, 'semicolonPC' },-- SMALL SEMICOLON
  ['less.pc'] = { 0xFE64, 'lessPC' },-- SMALL LESS-THAN SIGN
  ['equal.pc'] = { 0xFE66, 'equalPC' },-- SMALL EQUALS SIGN
  ['greater.pc'] = { 0xFE65, 'greaterPC' },-- SMALL GREATER-THAN SIGN
  ['question.pc'] = { 0xFE56, 'questionPC' },-- SMALL QUESTION MARK
  ['at.pc'] = { 0xFE6B, 'atPC' },-- SMALL COMMERCIAL AT
  ['braceleft.pc'] = { 0xFE5B, 'braceleftPC' },-- SMALL LEFT CURLY BRACKET
  ['braceright.pc'] = { 0xFE5C, 'bracerightPC' },-- SMALL RIGHT CURLY BRACKET
