  ['exclam.pc'] = { 0xFE57, 'exclamPC' },--﹗ SMALL EXCLAMATION MARK
  ['numbersign.pc'] = { 0xFE5F, 'numbersignPC' }, --﹟ SMALL NUMBER SIGN
  ['dollar.pc'] = { 0xFE69, 'dollarPC' },--＄ SMALL DOLLAR SIGN
  ['percent.pc'] = { 0xFE6A, 'percentPC' },--﹪ SMALL PERCENT SIGN
  ['ampersand.pc'] = { 0xFE60, 'ampersandPC' },--﹠ SMALL AMPERSAND
  ['parenleft.pc'] = { 0xFE59, 'parenleftPC' },--﹙ SMALL LEFT PARENTHESIS
  ['parenright.pc'] = { 0xFE5A, 'parenrightPC' },--﹚ SMALL RIGHT PARENTHESIS
  ['asterisk.pc'] = { 0xFE61, 'asteriskPC' },--﹡ SMALL ASTERISK
  ['plus.pc'] = { 0xFE62, 'plusPC' },--﹢ SMALL PLUS SIGN
  ['comma.pc'] = { 0xFE50, 'commaPC' },--﹐ SMALL COMMA
  ['hyphen.pc'] = { 0xFE63, 'hyphenPC' },--﹣ SMALL HYPHEN-MINUS
  ['period.pc'] = { 0xFE52, 'periodPC' },--﹒ SMALL FULL STOP
  ['slash.pc'] = { 0xFE68, 'slashPC' },--﹨ SMALL REVERSE SOLIDUS
  ['colon.pc'] = { 0xFE55, 'colonPC' },--﹕ SMALL COLON
  ['semicolon.pc'] = { 0xFE54, 'semicolonPC' },--﹔ SMALL SEMICOLON
  ['less.pc'] = { 0xFE64, 'lessPC' },--﹤ SMALL LESS-THAN SIGN
  ['equal.pc'] = { 0xFE66, 'equalPC' },--﹦ SMALL EQUALS SIGN
  ['greater.pc'] = { 0xFE65, 'greaterPC' },--﹥ SMALL GREATER-THAN SIGN
  ['question.pc'] = { 0xFE56, 'questionPC' },--﹖ SMALL QUESTION MARK
  ['at.pc'] = { 0xFE6B, 'atPC' },--﹫ SMALL COMMERCIAL AT
  ['commaturnedmod.pc'] = { 0xFE51, 'commaturnedmodPC' },--﹑ SMALL IDEOGRAPHIC COMMA
  ['emdash.pc'] = { 0xFE58, 'emdashPC' },--﹘ SMALL EM DASH
  ['braceleft.pc'] = { 0xFE5B, 'braceleftPC' },--﹛ SMALL LEFT CURLY BRACKET
  ['braceright.pc'] = { 0xFE5C, 'bracerightPC' },--﹜ SMALL RIGHT CURLY BRACKET
  ['tortoiseleft.pc'] = { 0xFE5D, 'tortoiseleftPC' },--﹝ SMALL LEFT TORTOISE SHELL BRACKET
  ['tortoiseright.pc'] = { 0xFE5E, 'tortoiserightPC' },--﹞ SMALL RIGHT TORTOISE SHELL BRACKET
