  ['zero.superior'] = { 0x2070, 'zerosuperscript' },-- SUPERSCRIPT ZERO
  ['one.superior'] = { 0x00B9, 'onesuperscript' },-- SUPERSCRIPT ONE
  ['two.superior'] = { 0x00B2, 'twosuperscript' },-- SUPERSCRIPT TWO
  ['three.superior'] = { 0x00B3, 'threesuperscript' },-- SUPERSCRIPT THREE
  ['four.superior'] = { 0x2074, 'foursuperscript' },-- SUPERSCRIPT FOUR
  ['five.superior'] = { 0x2075, 'fivesuperscript' },-- SUPERSCRIPT FIVE
  ['six.superior'] = { 0x2076, 'sixsuperscript' },-- SUPERSCRIPT SIX
  ['seven.superior'] = { 0x2077, 'sevensuperscript' },-- SUPERSCRIPT SEVEN
  ['eight.superior'] = { 0x2078, 'eightsuperscript' },-- SUPERSCRIPT EIGHT
  ['nine.superior'] = { 0x2079, 'ninesuperscript' },-- SUPERSCRIPT NINE

  ['arrowdown.superior'] = { 0xA71C, 'downarrowsuperscript' },--ꜜ Modifier Letter Raised Down Arrow
  ['arrowup.superior'] = { 0xA71B, 'arrowupsuperscript' },--ꜛ Modifier Letter Raised Up Arrow
  ['equal.superior'] = { 0x207C, 'equalsuperscript' },-- SUPERSCRIPT EQUALS SIGN
  ['exclam.superior'] = { 0xA71D, 'exclamsuperscript' },-- MODIFIER LETTER RAISED EXCLAMATION MARK
  ['exclamdown.superior'] = { 0xA71E, 'exclamdownsuperscript' },-- MODIFIER LETTER RAISED INVERTED EXCLAMATION MARK
  ['glottalstopreversed.superior'] = { 0x02E4, 'glottalstopreversedsuperscript' },-- MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
  ['minus.superior'] = { 0x207B, 'minussuperscript' },-- SUPERSCRIPT MINUS
  ['parenleft.superior'] = { 0x207D, 'parenleftsuperscript' },-- SUPERSCRIPT LEFT PARENTHESIS
  ['parenright.superior'] = { 0x207E, 'parenrightsuperscript' },-- SUPERSCRIPT RIGHT PARENTHESIS
  ['plus.superior'] = { 0x207A, 'plussuperscript' },-- SUPERSCRIPT PLUS SIGN

  ['A.superior'] = { 0x1D2C, 'Asuperscript' },-- MODIFIER LETTER CAPITAL A
  ['B.superior'] = { 0x1D2E, 'Bsuperscript' },-- MODIFIER LETTER CAPITAL B
  ['D.superior'] = { 0x1D30, 'Dsuperscript' },-- MODIFIER LETTER CAPITAL D
  ['E.superior'] = { 0x1D31, 'Esuperscript' },-- MODIFIER LETTER CAPITAL E
  ['G.superior'] = { 0x1D33, 'Gsuperscript' },-- MODIFIER LETTER CAPITAL G
  ['H.superior'] = { 0x1D34, 'Hsuperscript' },-- MODIFIER LETTER CAPITAL H
  ['I.superior'] = { 0x1D35, 'Isuperscript' },-- MODIFIER LETTER CAPITAL I
  ['J.superior'] = { 0x1D36, 'Jsuperscript' },-- MODIFIER LETTER CAPITAL J
  ['K.superior'] = { 0x1D37, 'Ksuperscript' },-- MODIFIER LETTER CAPITAL K
  ['L.superior'] = { 0x1D38, 'Lsuperscript' },-- MODIFIER LETTER CAPITAL L
  ['M.superior'] = { 0x1D39, 'Msuperscript' },-- MODIFIER LETTER CAPITAL M
  ['N.superior'] = { 0x1D3A, 'Nsuperscript' },-- MODIFIER LETTER CAPITAL N
  ['O.superior'] = { 0x1D3C, 'Osuperscript' },-- MODIFIER LETTER CAPITAL O
  ['P.superior'] = { 0x1D3E, 'Psuperscript' },-- MODIFIER LETTER CAPITAL P
  ['R.superior'] = { 0x1D3F, 'Rsuperscript' },-- MODIFIER LETTER CAPITAL R
  ['T.superior'] = { 0x1D40, 'Tsuperscript' },-- MODIFIER LETTER CAPITAL T
  ['U.superior'] = { 0x1D41, 'Usuperscript' },-- MODIFIER LETTER CAPITAL U
  ['V.superior'] = { 0x2C7D, 'Vsuperscript' },-- MODIFIER LETTER CAPITAL V
  ['W.superior'] = { 0x1D42, 'Wsuperscript' },-- MODIFIER LETTER CAPITAL W
  ['AE.superior'] = { 0x1D2D, 'AEsuperscript' },--ᴭ Modifier Letter Capital Ae
  ['Bbarred.superior'] = { 0x1D2F, 'Bbarredsuperscript' },--ᴯ Modifier Letter Capital Barred B
  ['Ereversed.superior'] = { 0x1D32, 'Ereversedsuperscript' },--ᴲ Modifier Letter Capital Reversed E
  ['Hbar.superior'] = { 0xA7F8, 'Hbarsuperscript' },--ꟸ Modifier Letter Capital H with Stroke
  ['Nturned.superior'] = { 0x1D3B, 'Nturnedsuperscript' },--ᴻ Modifier Letter Capital Reversed N
  ['Ou.superior'] = { 0x1D3D, 'Ousuperscript' },--ᴽ Modifier Letter Capital Ou

  ['AAsmall.superior'] = { 0x10780, 'AAsmallsuperscript' },--𐞀 Modifier Letter Small Capital Aa
  ['Bsmall.superior'] = { 0x10784, 'Bsmallsuperscript' },--𐞄 Modifier Letter Small Capital B
  ['Gsmall.superior'] = { 0x10792, 'Gsmallsuperscript' },--𐞒 Modifier Letter Small Capital G
  ['Gsmallhook.superior'] = { 0x10794, 'Gsmallhooksuperscript' },--𐞔 Modifier Letter Small Capital G With Hook
  ['Hsmall.superior'] = { 0x10796, 'Hsmallsuperscript' },--𐞖 Modifier Letter Small Capital H
  ['Ismall.superior'] = { 0x1DA6, 'Ismallsuperscript' },--ᶦ Modifier Letter Small Capital I
  ['Ismallstroke.superior'] = { 0x1DA7, 'Ismallstrokesuperscript' },--ᶧ Modifier Letter Small Capital I with Stroke
  ['Lsmall.superior'] = { 0x1DAB, 'Lsmallsuperscript' },--ᶫ Modifier Letter Small Capital L
  ['Lsmallbelt.superior'] = { 0x1079C, 'Lsmallbeltsuperscript' },--𐞜 Modifier Letter Small Capital L With Belt
  ['Nsmall.superior'] = { 0x1DB0, 'Nsmallsuperscript' },--ᶰ Modifier Letter Small Capital N
  ['OEsmall.superior'] = { 0x107A3, 'OEsmallsuperscript' },--𐞣 Modifier Letter Small Capital Oe
  ['Rsmall.superior'] = { 0x107AA, 'Rsmallsuperscript' },--𐞪 Modifier Letter Small Capital R
  ['Rsmallinverted.superior'] = { 0x02B6, 'Rsmallinvertedsuperscript'},-- MODIFIER LETTER SMALL CAPITAL INVERTED R
  ['Usmall.superior'] = { 0x1DB8, 'Usmallsuperscript' },--ᶸ Modifier Letter Small Capital U
  ['Ysmall.superior'] = { 0x107B2, 'Ysmallsuperscript' },--𐞲 Modifier Letter Small Capital Y

  ['a.superior'] = { 0x1D43, 'asuperscript' },-- MODIFIER LETTER SMALL A
  ['b.superior'] = { 0x1D47, 'bsuperscript' },-- MODIFIER LETTER SMALL B
  ['c.superior'] = { 0x1D9C, 'csuperscript' },-- MODIFIER LETTER SMALL C
  ['d.superior'] = { 0x1D48, 'dsuperscript' },-- MODIFIER LETTER SMALL D
  ['e.superior'] = { 0x1D49, 'esuperscript' },-- MODIFIER LETTER SMALL E
  ['f.superior'] = { 0x1DA0, 'fsuperscript' },-- MODIFIER LETTER SMALL F
  ['g.superior'] = { 0x1D4D, 'gsuperscript' },-- MODIFIER LETTER SMALL G
  ['h.superior'] = { 0x02B0, 'hsuperscript' },-- MODIFIER LETTER SMALL H
  ['i.superior'] = { 0x2071, 'isuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['j.superior'] = { 0x02B2, 'jsuperscript' },-- MODIFIER LETTER SMALL J
  ['k.superior'] = { 0x1D4F, 'ksuperscript' },-- MODIFIER LETTER SMALL K
  ['l.superior'] = { 0x02E1, 'lsuperscript' },-- MODIFIER LETTER SMALL L
  ['m.superior'] = { 0x1D50, 'msuperscript' },-- MODIFIER LETTER SMALL M
  ['n.superior'] = { 0x207F, 'nsuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER N
  ['o.superior'] = { 0x1D52, 'osuperscript' },-- MODIFIER LETTER SMALL O
  ['p.superior'] = { 0x1D56, 'psuperscript' },-- MODIFIER LETTER SMALL P
  ['q.superior'] = { 0x107A5, 'qsuperscript' },-- MODIFIER LETTER SMALL Q
  ['r.superior'] = { 0x02B3, 'rsuperscript' },-- MODIFIER LETTER SMALL R
  ['s.superior'] = { 0x02E2, 'ssuperscript' },-- MODIFIER LETTER SMALL S
  ['t.superior'] = { 0x1D57, 'tsuperscript' },-- MODIFIER LETTER SMALL T
  ['u.superior'] = { 0x1D58, 'usuperscript' },-- MODIFIER LETTER SMALL U
  ['v.superior'] = { 0x1D5B, 'vsuperscript' },-- MODIFIER LETTER SMALL V
  ['w.superior'] = { 0x02B7, 'wsuperscript' },-- MODIFIER LETTER SMALL W
  ['x.superior'] = { 0x02E3, 'xsuperscript' },-- MODIFIER LETTER SMALL X
  ['y.superior'] = { 0x02B8, 'ysuperscript' },-- MODIFIER LETTER SMALL Y
  ['z.superior'] = { 0x1DBB, 'zsuperscript' },-- MODIFIER LETTER SMALL Z

  ['ae.superior'] = { 0x10783, 'aesuperscript' },-- MODIFIER LETTER SMALL AE
  ['aeturned.superior'] = { 0x1D46, 'aeturnedsuperscript' },--ᵆ Modifier Letter Small Turned Ae
  ['aturned.superior'] = { 0x1D44, 'aturnedsuperscript' },--ᵄ Modifier Letter Small Turned A
  ['bhook.superior'] = { 0x10785, 'bhooksuperscript' },--𐞅 Modifier Letter Small B With Hook
  ['ccurl.superior'] = { 0x1D9D, 'ccurlsuperscript' },--ᶝ Modifier Letter Small C with Curl
  ['dezh.superior'] = { 0x1078A, 'dezhsuperscript' },--𐞊 Modifier Letter Small Dezh Digraph
  ['dhook.superior'] = { 0x1078C, 'dhooksuperscript' },--𐞌 Modifier Letter Small D With Hook
  ['dhooktail.superior'] = { 0x1078D, 'dhooktailsuperscript' },--𐞍 Modifier Letter Small D With Hook And Tail
  ['dtail.superior'] = { 0x1078B, 'dtailsuperscript' },--𐞋 Modifier Letter Small D With Tail
  ['dz.superior'] = { 0x10787, 'dzsuperscript' },--𐞇 Modifier Letter Small Dz Digraph
  ['dzcurl.superior'] = { 0x10789, 'dzcurlsuperscript' },--𐞉 Modifier Letter Small Dz Digraph With Curl
  ['dzhook.superior'] = { 0x10788, 'dzhooksuperscript' },--𐞈 Modifier Letter Small Dz Digraph With Retroflex Hook
  ['eng.superior'] = { 0x1D51, 'engsuperscript' },--ᵑ Modifier Letter Small Eng
  ['eopen.superior'] = { 0x1D4B, 'eopensuperscript' },--ᵋ Modifier Letter Small Open E
  ['eopenclosedreversed.superior'] = { 0x1078F, 'eopenclosedreversedsuperscript' },--𐞏 Modifier Letter Small Closed Reversed Open E
  ['eopeninverted.superior'] = { 0x1D4C, 'eopeninvertedsuperscript' },--ᵌ Modifier Letter Small Turned Open E
  ['eopenreversed.superior'] = { 0x1D9F, 'eopenreversedsuperscript' },--ᶟ Modifier Letter Small Reversed Open E
  ['esh.superior'] = { 0x1DB4, 'eshsuperscript' },--ᶴ Modifier Letter Small Esh
  ['eth.superior'] = { 0x1D9E, 'ethsuperscript' },--ᶞ Modifier Letter Small Eth
  ['eturned.superior'] = { 0x1078E, 'eturnedsuperscript' },--𐞎 Modifier Letter Small Reversed E
  ['ezh.superior'] = { 0x1DBE, 'ezhsuperscript' },--ᶾ	U+1DBE	Modifier Letter Small Ezh
  ['feng.superior'] = { 0x10790, 'fengsuperscript' },--𐞐 Modifier Letter Small Feng Digraph
  ['ghook.superior'] = { 0x10793, 'ghooksuperscript' },--𐞓 Modifier Letter Small G With Hook
  ['gscript.superior'] = { 0x10793, 'gscriptsuperscript' },--𐞓 Modifier Letter Small G With Hook
  ['hbar.superior'] = { 0x10795, 'hbarsuperscript' },--𐞕 Modifier Letter Small H With Stroke
  ['henghook.superior'] = { 0x10797, 'henghooksuperscript' },--𐞗 Modifier Letter Small Heng With Hook
  ['hhook.superior'] = { 0x02B1, 'hhooksuperscript' },-- MODIFIER LETTER SMALL H WITH HOOK
  ['hturned.superior'] = { 0x1DA3, 'hturnedsuperscript' },--ᶣ Modifier Letter Small Turned H
  ['iinverted.superior'] = { 0x1D4E, 'iinvertedsuperscript' },--ᵎ Modifier Letter Small Turned I
  ['istroke.superior'] = { 0x1DA4, 'istrokesuperscript' },--ᶤ Modifier Letter Small I with Stroke
  ['jcrossedtail.superior'] = { 0x1DA8, 'jcrossedtailsuperscript' },--ᶨ Modifier Letter Small J with Crossed-Tail
  ['jdotlessstroke.superior'] = { 0x1DA1, 'jdotlessstrokesuperscript' },--ᶡ Modifier Letter Small Dotless J with Stroke
  ['jhookstroke.superior'] = { 0x10798, 'jhookstrokesuperscript' },--𐞘 Modifier Letter Small Dotless J With Stroke And Hook
  ['lezh.superior'] = { 0x1079E, 'lezhsuperscript' },--𐞞 Modifier Letter Small Lezh
  ['lezhhook.superior'] = { 0x1079F, 'lezhhooksuperscript' },--𐞟 Modifier Letter Small Lezh With Retroflex Hook
  ['lhookbelt.superior'] = { 0x1079D, 'lhookbeltsuperscript' },--𐞝 Modifier Letter Small L With Retroflex Hook And Belt
  ['lhookretroflex.superior'] = { 0x1DA9, 'lhooksuperscript' },--ᶩ Modifier Letter Small L with Retroflex Hook
  ['llazys.superior'] = { 0xAB5D, 'llazyssuperscript' },--ꭝ Modifier Letter Small L with Inverted Lazy S
  ['lmiddletilde.superior'] = { 0xAB5E, 'lmiddletildesuperscript' },--ꭞ Modifier Letter Small L with Middle Tilde
  ['lpalat.superior'] = { 0x1DAA, 'lpalatsuperscript' },--ᶪ Modifier Letter Small L with Palatal Hook
  ['ls.superior'] = { 0x10799, 'lssuperscript' },--𐞙 Modifier Letter Small Ls Digraph
  ['lz.superior'] = { 0x1079A, 'lzsuperscript' },--𐞚 Modifier Letter Small Lz Digraph
  ['mhook.superior'] = { 0x1DAC, 'mhooksuperscript' },--ᶬ Modifier Letter Small M with Hook
  ['mlonglegturned.superior'] = { 0x1DAD, 'mlonglegturnedsuperscript' },--ᶭ Modifier Letter Small Turned M with Long Leg
  ['mturned.superior'] = { 0x1D5A, 'mturnedsuperscript' },--ᵚ Modifier Letter Small Turned M
  ['nhookleft.superior'] = { 0x1DAE, 'nhookleftsuperscript' },--ᶮ Modifier Letter Small N with Left Hook
  ['nhookretroflex.superior'] = { 0x1DAF, 'nhooksuperscript' },--ᶯ Modifier Letter Small N with Retroflex Hook
  ['obarred.superior'] = { 0x1DB1, 'obarredsuperscript' },--ᶱ Modifier Letter Small Barred O
  ['oe.superior'] = { 0xA7F9, 'oesuperscript' },--ꟹ Modifier Letter Small Ligature Oe
  ['oopen.superior'] = { 0x1D53, 'oopensuperscript' },--ᵓ Modifier Letter Small Open O
  ['oslash.superior'] = { 0x107A2, 'oslashsuperscript' },--𐞢 Modifier Letter Small O With Stroke
  ['rfishhook.superior'] = { 0x107A9, 'rfishhooksuperscript' },--𐞩 Modifier Letter Small R With Fishhook
  ['rhook.superior'] = { 0x107A8, 'rhooksuperscript' },--𐞨 Modifier Letter Small R With Tail
  ['rhookturned.superior'] = { 0x02B5, 'rhookturnedsuperscript' },-- MODIFIER LETTER SMALL TURNED R WITH HOOK
  ['rleghookinverted.superior'] = { 0x107A7, 'rleghookinvertedsuperscript' },--𐞧 Modifier Letter Small Turned R With Long Leg And Retroflex Hook
  ['rlonglegturned.superior'] = { 0x107A6, 'rlonglegturnedsuperscript' },--𐞦 Modifier Letter Small Turned R With Long Leg
  ['rturned.superior'] = { 0x02B4, 'rturnedsuperscript' },-- MODIFIER LETTER SMALL TURNED R
  ['scurl.superior'] = { 0x107BA, 'scurlsuperscript' },--𐞺 Modifier Letter Small S With Curl
  ['shook.superior'] = { 0x1DB3, 'shooksuperscript' },--ᶳ Modifier Letter Small S with Hook
  ['shwa.superior'] = { 0x1D4A, 'shwasuperscript' },--ᵊ Modifier Letter Small Schwa
  ['tccurl.superior'] = { 0x107AB, 'tccurlsuperscript' },--𐞫 Modifier Letter Small Tc Digraph With Curl
  ['tesh.superior'] = { 0x107AE, 'teshsuperscript' },--𐞮 Modifier Letter Small Tesh Digraph
  ['tpalatalhook.superior'] = { 0x1DB5, 'tlefthooksuperscript' },--ᶵ Modifier Letter Small T with Palatal Hook
  ['tretroflexhook.superior'] = { 0x107AF, 'thooksuperscript' },--𐞯 Modifier Letter Small T With Retroflex Hook
  ['ts.superior'] = { 0x107AC, 'tssuperscript' },--𐞬 Modifier Letter Small Ts Digraph
  ['tshook.superior'] = { 0x107AD, 'tskooksuperscript' },--𐞭 Modifier Letter Small Ts Digraph With Retroflex Hook
  ['ubar.superior'] = { 0x1DB6, 'ubarsuperscript' },--ᶶ Modifier Letter Small U Bar
  ['ulefthook.superior'] = { 0xAB5F, 'ulefthooksuperscript' },--ꭟ Modifier Letter Small U with Left Hook
  ['uturned.superior'] = { 0x1D59, 'uturnedsuperscript' },--ᵙ Modifier Letter Small Sideways U
  ['vhook.superior'] = { 0x1DB9, 'vhooksuperscript' },--ᶹ Modifier Letter Small V with Hook
  ['vrighthook.superior'] = { 0x107B0, 'vrighthooksuperscript' },--𐞰 Modifier Letter Small V With Right Hook
  ['vturned.superior'] = { 0x1DBA, 'vturnedsuperscript' },--ᶺ Modifier Letter Small Turned V
  ['wturned.superior'] = { 0xAB69, 'wturnedsuperscript' },--ꭩ Modifier Letter Small Turned W
  ['ybeltturned.superior'] = { 0x107A1, 'ybeltturnedsuperscript' },--𐞡 Modifier Letter Small Turned Y With Belt
  ['yturned.superior'] = { 0x107A0, 'yturnedsuperscript' },--𐞠 Modifier Letter Small Turned Y
  ['zcurl.superior'] = { 0x1DBD, 'zcurlsuperscript' },--ᶽ Modifier Letter Small Z with Curl
  ['zretroflexhook.superior'] = { 0x1DBC, 'zhooksuperscript' },--ᶼ Modifier Letter Small Z with Retroflex Hook

  ['gammalatin.superior'] = { 0x02E0, 'gammalatinsuperscript' },-- MODIFIER LETTER SMALL GAMMA
  ['alpha.superior'] = { 0x1D45, 'alphasuperscript' },--ᵅ Modifier Letter Small Alpha
  ['alphaturned.superior'] = { 0x1D9B, 'alphaturnedsuperscript' },--ᶛ Modifier Letter Small Turned Alpha
  ['beta.superior'] = { 0x1D5D, 'betasuperscript' },--ᵝ Modifier Letter Small Beta
  ['gamma.superior'] = { 0x02E0, 'gammasuperscript' },--ˠ Modifier Letter Small Gamma
  ['greekgamma.superior'] = { 0x1D5E, 'greekgammasuperscript' },--ᵞ Modifier Letter Small Greek Gamma
  ['delta.superior'] = { 0x1D5F, 'deltasuperscript' },--ᵟ Modifier Letter Small Delta
  ['iota.superior'] = { 0x1DA5, 'iotasuperscript' },--ᶥ Modifier Letter Small Iota
  ['phi1.superior'] = { 0x1DB2, 'phi1superscript' },--ᶲ Modifier Letter Small Phi
  ['upsilon.superior'] = { 0x1DB7, 'upsilonsuperscript' },--ᶷ Modifier Letter Small Upsilon
  ['theta.superior'] = { 0x1DBF, 'thetasuperscript' },--ᶿ Modifier Letter Small Theta
  ['phi.superior'] = { 0x1D60, 'phisuperscript' },--ᵠ Modifier Letter Small Greek Phi
  ['chi.superior'] = { 0x1D61, 'chisuperscript' },--ᵡ Modifier Letter Small Chi
  ['omegalatinclosed.superior'] = { 0x107A4, 'omegalatinclosedsuperscript' },--𐞤 Modifier Letter Small Closed Omega


  ['acyr.superior'] = { 0x1E030, 'acyrsuperscript' },--𞀰 Modifier Letter Cyrillic Small A
  ['becyr.superior'] = { 0x1E031, 'becyrsuperscript' },--𞀱 Modifier Letter Cyrillic Small Be
  ['vecyr.superior'] = { 0x1E032, 'vecyrsuperscript' },--𞀲 Modifier Letter Cyrillic Small Ve
  ['ghecyr.superior'] = { 0x1E033, 'ghecyrsuperscript' },--𞀳 Modifier Letter Cyrillic Small Ghe
  ['decyr.superior'] = { 0x1E034, 'decyrsuperscript' },--𞀴 Modifier Letter Cyrillic Small De
  ['iecyr.superior'] = { 0x1E035, 'iecyrsuperscript' },--𞀵 Modifier Letter Cyrillic Small Ie
  ['zhecyr.superior'] = { 0x1E036, 'zhecyrsuperscript' },--𞀶 Modifier Letter Cyrillic Small Zhe
  ['zecyr.superior'] = { 0x1E037, 'zecyrsuperscript' },--𞀷 Modifier Letter Cyrillic Small Ze
  ['iicyr.superior'] = { 0x1E038, 'iicyrsuperscript' },--𞀸 Modifier Letter Cyrillic Small I
  ['palochkacyr.superior'] = { 0x1E050, 'palochkacyrsuperscript' },--𞁐 Modifier Letter Cyrillic Small Palochka
  ['kacyr.superior'] = { 0x1E039, 'kacyrsuperscript' },--𞀹 Modifier Letter Cyrillic Small Ka
  ['elcyr.superior'] = { 0x1E03A, 'elcyrsuperscript' },--𞀺 Modifier Letter Cyrillic Small El
  ['emcyr.superior'] = { 0x1E03B, 'emcyrsuperscript' },--𞀻 Modifier Letter Cyrillic Small Em
  ['encyr.superior'] = { 0x1D78, 'encyrsuperscript' },--ᵸ Modifier Letter Cyrillic Small En
  ['ocyr.superior'] = { 0x1E03C, 'ocyrsuperscript' },--𞀼 Modifier Letter Cyrillic Small O
  ['obarredcyr.superior'] = { 0x1E04E, 'obarredcyrsuperscript' },--𞁎 Modifier Letter Cyrillic Small Barred O
  ['pecyr.superior'] = { 0x1E03D, 'pecyrsuperscript' },--𞀽 Modifier Letter Cyrillic Small Pe
  ['ercyr.superior'] = { 0x1E03E, 'ercyrsuperscript' },--𞀾 Modifier Letter Cyrillic Small Er
  ['escyr.superior'] = { 0x1E03F, 'escyrsuperscript' },--𞀿 Modifier Letter Cyrillic Small Es
  ['esdescendercyr.superior'] = { 0x1E06B, 'esdescendercyrsuperscript' },--𞁫 Modifier Letter Cyrillic Small Es With Descender
  ['tecyr.superior'] = { 0x1E040, 'tecyrsuperscript' },--𞁀 Modifier Letter Cyrillic Small Te
  ['ucyr.superior'] = { 0x1E041, 'ucyrsuperscript' },--𞁁 Modifier Letter Cyrillic Small U
  ['ustraightcyr.superior'] = { 0x1E04F, 'ustraightcyrsuperscript' },--𞁏 Modifier Letter Cyrillic Small Straight U
  ['ustraightstrokecyr.superior'] = { 0x1E06D, 'ustraightstrokecyrsuperscript' },--𞁭 Modifier Letter Cyrillic Small Straight U With Stroke
  ['efcyr.superior'] = { 0x1E042, 'efcyrsuperscript' },--𞁂 Modifier Letter Cyrillic Small Ef
  ['hacyr.superior'] = { 0x1E043, 'hacyrsuperscript' },--𞁃 Modifier Letter Cyrillic Small Ha
  ['tsecyr.superior'] = { 0x1E044, 'tsecyrsuperscript' },--𞁄 Modifier Letter Cyrillic Small Tse
  ['checyr.superior'] = { 0x1E045, 'checyrsuperscript' },--𞁅 Modifier Letter Cyrillic Small Che
  ['shacyr.superior'] = { 0x1E046, 'shacyrsuperscript' },--𞁆 Modifier Letter Cyrillic Small Sha
  ['yerucyr.superior'] = { 0x1E047, 'yerucyrsuperscript' },--𞁇 Modifier Letter Cyrillic Small Yeru
  ['yerubackcyr.superior'] = { 0x1E06C, 'yerubackcyrsuperscript' },--𞁬 Modifier Letter Cyrillic Small Yeru With Back Yer
  ['ecyr.superior'] = { 0x1E048, 'ecyrsuperscript' },--𞁈 Modifier Letter Cyrillic Small E
  ['yucyr.superior'] = { 0x1E049, 'yucyrsuperscript' },--𞁉 Modifier Letter Cyrillic Small Yu
  ['dzzecyr.superior'] = { 0x1E04A, 'dzzecyrsuperscript' },--𞁊 Modifier Letter Cyrillic Small Dzze
  ['schwacyr.superior'] = { 0x1E04B, 'schwacyrsuperscript' },--𞁋 Modifier Letter Cyrillic Small Schwa
  ['icyr.superior'] = { 0x1E04C, 'icyrsuperscript' },--𞁌 Modifier Letter Cyrillic Small Byelorussian-Ukrainian I
  ['jecyr.superior'] = { 0x1E04D, 'jecyrsuperscript' },--𞁍 Modifier Letter Cyrillic Small Je
  ['softsign.superior'] = { 0xA69D, 'softsignsuperscript' },--ꚝ U+A69D Modifier Letter Cyrillic Soft Sign
  ['hardsign.superior'] = { 0xA69D, 'hardsignsuperscript' },--ꚜ U+A69C Modifier Letter Cyrillic Hard Sign
