return {
  ['Aacutesmall'] = { 0x1D00, 0x0301 },-- LATIN LETTER SMALL CAPITAL A/COMBINING ACUTE ACCENT
  ['Acircumflexsmall'] = { 0x1D00, 0x0302 },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT
  ['Acute'] = { 0x00B4 },-- ACUTE ACCENT
  ['Acutesmall'] = { 0x00B4 },-- ACUTE ACCENT
  ['Adieresissmall'] = { 0x1D00, 0x0308 },-- LATIN LETTER SMALL CAPITAL A/COMBINING DIAERESIS
  ['AEsmall'] = { 0x1D01 },-- LATIN LETTER SMALL CAPITAL AE
  ['afii10063'] = { 0x0433 },-- CYRILLIC SMALL LETTER GHE
  ['afii10064'] = { 0x0431 },-- CYRILLIC SMALL LETTER BE
  ['afii10192'] = { 0x0434 },-- CYRILLIC SMALL LETTER DE
  ['afii10831'] = { 0x043F },-- CYRILLIC SMALL LETTER PE
  ['afii10832'] = { 0x0442 },-- CYRILLIC SMALL LETTER TE
  ['Agravesmall'] = { 0x1D00, 0x0300 },-- LATIN LETTER SMALL CAPITAL A/COMBINING GRAVE ACCENT
  ['ampersandsmall'] = { 0xFE60 },-- SMALL AMPERSAND
  ['Aringsmall'] = { 0x1D00, 0x030A },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE
  ['arrowhorizex'] = { 0x23AF },-- HORIZONTAL LINE EXTENSION
  ['arrowvertex'] = { 0x23D0 },-- VERTICAL LINE EXTENSION
  ['Asmall'] = { 0x1D00 },-- LATIN LETTER SMALL CAPITAL A
  ['asuperior'] = { 0x00AA },-- FEMININE ORDINAL INDICATOR
  ['Atildesmall'] = { 0x1D00, 0x0303 },-- LATIN LETTER SMALL CAPITAL A/COMBINING TILDE
  ['braceex'] = { 0x23AA },-- CURLY BRACKET EXTENSION
  ['braceleftbt'] = { 0x23A9 },-- LEFT CURLY BRACKET LOWER HOOK
  ['braceleftmid'] = { 0x23A8 },-- LEFT CURLY BRACKET MIDDLE PIECE
  ['bracelefttp'] = { 0x23A7 },-- LEFT CURLY BRACKET UPPER HOOK
  ['bracerightbt'] = { 0x23AD },-- RIGHT CURLY BRACKET LOWER HOOK
  ['bracerightmid'] = { 0x23AC },-- RIGHT CURLY BRACKET MIDDLE PIECE
  ['bracerighttp'] = { 0x23AB },-- RIGHT CURLY BRACKET UPPER HOOK
  ['bracketleftbt'] = { 0x23A3 },-- LEFT SQUARE BRACKET LOWER CORNER
  ['bracketleftex'] = { 0x23A2 },-- LEFT SQUARE BRACKET EXTENSION
  ['bracketlefttp'] = { 0x23A1 },-- LEFT SQUARE BRACKET UPPER CORNER
  ['bracketrightbt'] = { 0x23A6 },-- RIGHT SQUARE BRACKET LOWER CORNER
  ['bracketrightex'] = { 0x23A5 },-- RIGHT SQUARE BRACKET EXTENSION
  ['bracketrighttp'] = { 0x23A4 },-- RIGHT SQUARE BRACKET UPPER CORNER
  ['Brevesmall'] = { 0x02D8 },-- BREVE
  ['Bsmall'] = { 0x0299 },-- LATIN LETTER SMALL CAPITAL B
  ['bsuperior'] = { 0x1D47 },-- MODIFIER LETTER SMALL B
  ['Caron'] = { 0x02C7 },-- CARON
  ['Caronsmall'] = { 0x02C7 },-- CARON
  ['Ccedillasmall'] = { 0x1D04, 0x0327 },-- LATIN LETTER SMALL CAPITAL C/COMBINING CEDILLA
  ['Cedillasmall'] = { 0x00B8 },-- CEDILLA
  ['centinferior'] = { 0x00A2 },-- CENT SIGN
  ['centoldstyle'] = { 0x00A2 },-- CENT SIGN
  ['centsuperior'] = { 0x00A2 },-- CENT SIGN
  ['Circumflexsmall'] = { 0x02C6 },-- MODIFIER LETTER CIRCUMFLEX ACCENT
  ['commaaccent'] = { 0x0326 },-- COMBINING COMMA BELOW
  ['commainferior'] = { 0x002C },-- COMMA
  ['commasuperior'] = { 0x002C },-- COMMA
  ['copyrightsans'] = { 0x00A9 },-- COPYRIGHT SIGN
  ['copyrightserif'] = { 0x00A9 },-- COPYRIGHT SIGN
  ['Csmall'] = { 0x1D04 },-- LATIN LETTER SMALL CAPITAL C
  ['cyrBreve'] = { 0x02D8 },-- BREVE
  ['cyrbreve'] = { 0x02D8 },-- BREVE
  ['cyrFlex'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['cyrflex'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['dblGrave'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['dblgrave'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['Dieresis'] = { 0x00A8 },-- DIAERESIS
  ['dieresisacute'] = { 0x0308, 0x0301 },-- COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['DieresisAcute'] = { 0x1DC1 },-- COMBINING DOTTED ACUTE ACCENT
  ['dieresisgrave'] = { 0x0308, 0x0300 },-- COMBINING DIAERESIS/COMBINING GRAVE ACCENT
  ['DieresisGrave'] = { 0x1DC0 },-- COMBINING DOTTED GRAVE ACCENT
  ['Dieresissmall'] = { 0x00A8 },-- DIAERESIS
  ['dollarinferior'] = { 0x0024 },-- DOLLAR SIGN
  ['dollaroldstyle'] = { 0x0024 },-- DOLLAR SIGN
  ['dollarsuperior'] = { 0x0024 },-- DOLLAR SIGN
  ['Dotaccentsmall'] = { 0x02D9 },-- DOT ABOVE
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['Dsmall'] = { 0x1D05 },-- LATIN LETTER SMALL CAPITAL D
  ['dsuperior'] = { 0x1D48 },-- MODIFIER LETTER SMALL D
  ['Eacutesmall'] = { 0x1D07, 0x0301 },-- LATIN LETTER SMALL CAPITAL E/COMBINING ACUTE ACCENT
  ['Ecircumflexsmall'] = { 0x1D07, 0x0302 },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT
  ['Edieresissmall'] = { 0x1D07, 0x0308 },-- LATIN LETTER SMALL CAPITAL E/COMBINING DIAERESIS
  ['Egravesmall'] = { 0x1D07, 0x0300 },-- LATIN LETTER SMALL CAPITAL E/COMBINING GRAVE ACCENT
  ['eightoldstyle'] = { 0x0038 },-- DIGIT EIGHT
  ['Esmall'] = { 0x1D07 },-- LATIN LETTER SMALL CAPITAL E
  ['esuperior'] = { 0x1D49 },-- MODIFIER LETTER SMALL E
  ['Ethsmall'] = { 0x1D06 },-- LATIN LETTER SMALL CAPITAL ETH
  ['exclamdownsmall'] = { 0x00A1 },-- INVERTED EXCLAMATION MARK
  ['exclamsmall'] = { 0xFE57 },-- SMALL EXCLAMATION MARK
  ['fiveoldstyle'] = { 0x0035 },-- DIGIT FIVE
  ['fouroldstyle'] = { 0x0034 },-- DIGIT FOUR
  ['Fsmall'] = { 0xA730 },-- LATIN LETTER SMALL CAPITAL F
  ['Grave'] = { 0x0060 },-- GRAVE ACCENT
  ['Gravesmall'] = { 0x0060 },-- GRAVE ACCENT
  ['Gsmall'] = { 0x0262 },-- LATIN LETTER SMALL CAPITAL G
  ['Hsmall'] = { 0x029C },-- LATIN LETTER SMALL CAPITAL H
  ['Hungarumlaut'] = { 0x02DD },-- DOUBLE ACUTE ACCENT
  ['Hungarumlautsmall'] = { 0x02DD },-- DOUBLE ACUTE ACCENT
  ['hypheninferior'] = { 0x002D },-- HYPHEN-MINUS
  ['hyphensuperior'] = { 0x207B },-- SUPERSCRIPT MINUS
  ['Iacutesmall'] = { 0x026A, 0x0301 },-- LATIN LETTER SMALL CAPITAL I/COMBINING ACUTE ACCENT
  ['Icircumflexsmall'] = { 0x026A, 0x0302 },-- LATIN LETTER SMALL CAPITAL I/COMBINING CIRCUMFLEX ACCENT
  ['Idieresissmall'] = { 0x026A, 0x0308 },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS
  ['Igravesmall'] = { 0x026A, 0x0300 },-- LATIN LETTER SMALL CAPITAL I/COMBINING GRAVE ACCENT
  ['integralex'] = { 0x23AE },-- INTEGRAL EXTENSION
  ['Ismall'] = { 0x026A },-- LATIN LETTER SMALL CAPITAL I
  ['isuperior'] = { 0x2071 },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['Jsmall'] = { 0x1D0A },-- LATIN LETTER SMALL CAPITAL J
  ['Ksmall'] = { 0x1D0B },-- LATIN LETTER SMALL CAPITAL K
  ['lamedholamdagesh'] = { 0x05DC, 0x05B9, 0x05BC, },-- HEBREW LETTER LAMED/HEBREW POINT HOLAM/HEBREW POINT DAGESH OR MAPIQ
  ['lamedholamdageshhebrew'] = { 0x05DC, 0x05B9, 0x05BC, },-- HEBREW LETTER LAMED/HEBREW POINT HOLAM/HEBREW POINT DAGESH OR MAPIQ
  ['lammeemjeeminitialarabic'] = { 0xFEDF, 0xFEE4, 0xFEA0, },-- ARABIC LETTER LAM INITIAL FORM/ARABIC LETTER MEEM MEDIAL FORM/ARABIC LETTER JEEM MEDIAL FORM
  ['lammeemkhahinitialarabic'] = { 0xFEDF, 0xFEE4, 0xFEA8, },-- ARABIC LETTER LAM INITIAL FORM/ARABIC LETTER MEEM MEDIAL FORM/ARABIC LETTER KHAH MEDIAL FORM
  ['LL'] = { 0x004C, 0x004C },-- LATIN CAPITAL LETTER L/LATIN CAPITAL LETTER L
  ['ll'] = { 0x006C, 0x006C },-- LATIN SMALL LETTER L/LATIN SMALL LETTER L
  ['Lslashsmall'] = { 0x1D0C },-- LATIN LETTER SMALL CAPITAL L WITH STROKE
  ['Lsmall'] = { 0x029F },-- LATIN LETTER SMALL CAPITAL L
  ['lsuperior'] = { 0x02E1 },-- MODIFIER LETTER SMALL L
  ['Macron'] = { 0x00AF },-- MACRON
  ['Macronsmall'] = { 0x00AF },-- MACRON
  ['Msmall'] = { 0x1D0D },-- LATIN LETTER SMALL CAPITAL M
  ['msuperior'] = { 0x1D50 },-- MODIFIER LETTER SMALL M
  ['nineoldstyle'] = { 0x0039 },-- DIGIT NINE
  ['Nsmall'] = { 0x0274 },-- LATIN LETTER SMALL CAPITAL N
  ['Ntildesmall'] = { 0x0274, 0x0303 },-- LATIN LETTER SMALL CAPITAL N/COMBINING TILDE
  ['Oacutesmall'] = { 0x1D0F, 0x0301 },-- LATIN LETTER SMALL CAPITAL O/COMBINING ACUTE ACCENT
  ['Ocircumflexsmall'] = { 0x1D0F, 0x0302 },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT
  ['Odieresissmall'] = { 0x1D0F, 0x0308 },-- LATIN LETTER SMALL CAPITAL O/COMBINING DIAERESIS
  ['OEsmall'] = { 0x0276 },-- LATIN LETTER SMALL CAPITAL OE
  ['Ogoneksmall'] = { 0x02DB },-- OGONEK
  ['Ogravesmall'] = { 0x1D0F, 0x0300 },-- LATIN LETTER SMALL CAPITAL O/COMBINING GRAVE ACCENT
  ['onefitted'] = { 0x0031 },-- DIGIT ONE
  ['oneoldstyle'] = { 0x0031 },-- DIGIT ONE
  ['Oslashsmall'] = { 0x00F8 },-- LATIN SMALL LETTER O WITH STROKE
  ['Osmall'] = { 0x1D0F },-- LATIN LETTER SMALL CAPITAL O
  ['osuperior'] = { 0x00BA },-- MASCULINE ORDINAL INDICATOR
  ['Otildesmall'] = { 0x1D0F, 0x0303 },-- LATIN LETTER SMALL CAPITAL O/COMBINING TILDE
  ['parenleftbt'] = { 0x239D },-- LEFT PARENTHESIS LOWER HOOK
  ['parenleftex'] = { 0x239C },-- LEFT PARENTHESIS EXTENSION
  ['parenlefttp'] = { 0x239B },-- LEFT PARENTHESIS UPPER HOOK
  ['parenrightbt'] = { 0x23A0 },-- RIGHT PARENTHESIS LOWER HOOK
  ['parenrightex'] = { 0x239F },-- RIGHT PARENTHESIS EXTENSION
  ['parenrighttp'] = { 0x239E },-- RIGHT PARENTHESIS UPPER HOOK
  ['periodinferior'] = { 0x002E },-- FULL STOP
  ['periodsuperior'] = { 0x002E },-- FULL STOP
  ['Psmall'] = { 0x1D18 },-- LATIN LETTER SMALL CAPITAL P
  ['Qsmall'] = { 0xA7AF },-- LATIN LETTER SMALL CAPITAL Q
  ['questiondownsmall'] = { 0x00BF },-- INVERTED QUESTION MARK
  ['questionsmall'] = { 0xFE56 },-- SMALL QUESTION MARK
  ['radicalex'] = { 0x23D0 },-- VERTICAL LINE EXTENSION
  ['registersans'] = { 0x00AE },-- REGISTERED SIGN
  ['registerserif'] = { 0x00AE },-- REGISTERED SIGN
  ['rehyehaleflamarabic'] = { 0x0631, 0xFEF3, 0xFE8E, 0x0644, },-- ARABIC LETTER REH/ARABIC LETTER YEH INITIAL FORM/ARABIC LETTER ALEF FINAL FORM/ARABIC LETTER LAM
  ['Ringsmall'] = { 0x02DA },-- RING ABOVE
  ['Rsmall'] = { 0x0280 },-- LATIN LETTER SMALL CAPITAL R
  ['rsuperior'] = { 0x02B3 },-- MODIFIER LETTER SMALL R
  ['rupiah'] = { 0x20A8 },-- RUPEE SIGN
  ['Scaronsmall'] = { 0xA731, 0x030C },-- LATIN LETTER SMALL CAPITAL S/COMBINING CARON
  ['sevenoldstyle'] = { 0x0037 },-- DIGIT SEVEN
  ['sixoldstyle'] = { 0x0036 },-- DIGIT SIX
  ['Ssmall'] = { 0xA731 },-- LATIN LETTER SMALL CAPITAL S
  ['ssuperior'] = { 0x02E2 },-- MODIFIER LETTER SMALL S
  ['Thornsmall'] = { 0x00FE },-- LATIN SMALL LETTER THORN
  ['threeoldstyle'] = { 0x0033 },-- DIGIT THREE
  ['threequartersemdash'] = { 0x2014 },-- EM DASH
  ['Tildesmall'] = { 0x02DC },-- SMALL TILDE
  ['trademarksans'] = { 0x2122 },-- TRADE MARK SIGN
  ['trademarkserif'] = { 0x2122 },-- TRADE MARK SIGN
  ['Tsmall'] = { 0x1D1B },-- LATIN LETTER SMALL CAPITAL T
  ['tsuperior'] = { 0x1D57 },-- MODIFIER LETTER SMALL T
  ['twooldstyle'] = { 0x0032 },-- DIGIT TWO
  ['Uacutesmall'] = { 0x1D1C, 0x0301 },-- LATIN LETTER SMALL CAPITAL U/COMBINING ACUTE ACCENT
  ['Ucircumflexsmall'] = { 0x1D1C, 0x0302 },-- LATIN LETTER SMALL CAPITAL U/COMBINING CIRCUMFLEX ACCENT
  ['Udieresissmall'] = { 0x1D1C, 0x0308 },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS
  ['Ugravesmall'] = { 0x1D1C, 0x0300 },-- LATIN LETTER SMALL CAPITAL U/COMBINING GRAVE ACCENT
  ['Usmall'] = { 0x1D1C },-- LATIN LETTER SMALL CAPITAL U
  ['Vsmall'] = { 0x1D20 },-- LATIN LETTER SMALL CAPITAL V
  ['Wsmall'] = { 0x1D21 },-- LATIN LETTER SMALL CAPITAL W
  ['Xsmall'] = { 0x0078 },-- LATIN SMALL LETTER X
  ['Yacutesmall'] = { 0x028F, 0x0301 },-- LATIN LETTER SMALL CAPITAL Y/COMBINING ACUTE ACCENT
  ['Ydieresissmall'] = { 0x028F, 0x0308 },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DIAERESIS
  ['Ysmall'] = { 0x028F },-- LATIN LETTER SMALL CAPITAL Y
  ['Zcaronsmall'] = { 0x1D22, 0x030C },-- LATIN LETTER SMALL CAPITAL Z/COMBINING CARON
  ['zerooldstyle'] = { 0x0030 },-- DIGIT ZERO
  ['Zsmall'] = { 0x1D22 },-- LATIN LETTER SMALL CAPITAL Z
}
