return {
  ['AEsmall'] = { 0x00E6 },-- LATIN SMALL LETTER AE
  ['Aacutesmall'] = { 0x00E1 },-- LATIN SMALL LETTER A WITH ACUTE
  ['Acircumflexsmall'] = { 0x00E2 },-- LATIN SMALL LETTER A WITH CIRCUMFLEX
  ['Acute'] = { 0x00B4 },-- ACUTE ACCENT
  ['Acutesmall'] = { 0x00B4 },-- ACUTE ACCENT
  ['Adieresissmall'] = { 0x00E4 },-- LATIN SMALL LETTER A WITH DIAERESIS
  ['Agravesmall'] = { 0x00E0 },-- LATIN SMALL LETTER A WITH GRAVE
  ['Aringsmall'] = { 0x00E5 },-- LATIN SMALL LETTER A WITH RING ABOVE
  ['Asmall'] = { 0x0061 },-- LATIN SMALL LETTER A
  ['Atildesmall'] = { 0x00E3 },-- LATIN SMALL LETTER A WITH TILDE
  ['Brevesmall'] = { 0x02D8 },-- BREVE
  ['Bsmall'] = { 0x0062 },-- LATIN SMALL LETTER B
  ['Caron'] = { 0x02C7 },-- CARON
  ['Caronsmall'] = { 0x02C7 },-- CARON
  ['Ccedillasmall'] = { 0x00E7 },-- LATIN SMALL LETTER C WITH CEDILLA
  ['Cedillasmall'] = { 0x00B8 },-- CEDILLA
  ['Circumflexsmall'] = { 0x02C6 },-- MODIFIER LETTER CIRCUMFLEX ACCENT
  ['Csmall'] = { 0x0063 },-- LATIN SMALL LETTER C
  ['Dieresis'] = { 0x00A8 },-- DIAERESIS
  ['DieresisAcute'] = { 0x1DC1 },-- COMBINING DOTTED ACUTE ACCENT
  ['DieresisGrave'] = { 0x1DC0 },-- COMBINING DOTTED GRAVE ACCENT
  ['Dieresissmall'] = { 0x00A8 },-- DIAERESIS
  ['Dotaccentsmall'] = { 0x02D9 },-- DOT ABOVE
  ['Dsmall'] = { 0x0064 },-- LATIN SMALL LETTER D
  ['Eacutesmall'] = { 0x00E9 },-- LATIN SMALL LETTER E WITH ACUTE
  ['Ecircumflexsmall'] = { 0x00EA },-- LATIN SMALL LETTER E WITH CIRCUMFLEX
  ['Edieresissmall'] = { 0x00EB },-- LATIN SMALL LETTER E WITH DIAERESIS
  ['Egravesmall'] = { 0x00E8 },-- LATIN SMALL LETTER E WITH GRAVE
  ['Esmall'] = { 0x0065 },-- LATIN SMALL LETTER E
  ['Ethsmall'] = { 0x00F0 },-- LATIN SMALL LETTER ETH
  ['Fsmall'] = { 0x0066 },-- LATIN SMALL LETTER F
  ['Grave'] = { 0x0060 },-- GRAVE ACCENT
  ['Gravesmall'] = { 0x0060 },-- GRAVE ACCENT
  ['Gsmall'] = { 0x0067 },-- LATIN SMALL LETTER G
  ['Hsmall'] = { 0x0068 },-- LATIN SMALL LETTER H
  ['Hungarumlaut'] = { 0x02DD },-- DOUBLE ACUTE ACCENT
  ['Hungarumlautsmall'] = { 0x02DD },-- DOUBLE ACUTE ACCENT
  ['Iacutesmall'] = { 0x00ED },-- LATIN SMALL LETTER I WITH ACUTE
  ['Icircumflexsmall'] = { 0x00EE },-- LATIN SMALL LETTER I WITH CIRCUMFLEX
  ['Idieresissmall'] = { 0x00EF },-- LATIN SMALL LETTER I WITH DIAERESIS
  ['Igravesmall'] = { 0x00EC },-- LATIN SMALL LETTER I WITH GRAVE
  ['Ismall'] = { 0x0069 },-- LATIN SMALL LETTER I
  ['Jsmall'] = { 0x006A },-- LATIN SMALL LETTER J
  ['Ksmall'] = { 0x006B },-- LATIN SMALL LETTER K
  ['LL'] = { 0x004C, 0x004C },-- LATIN CAPITAL LETTER L/LATIN CAPITAL LETTER L
  ['Lslashsmall'] = { 0x0142 },-- LATIN SMALL LETTER L WITH STROKE
  ['Lsmall'] = { 0x006C },-- LATIN SMALL LETTER L
  ['Macron'] = { 0x00AF },-- MACRON
  ['Macronsmall'] = { 0x00AF },-- MACRON
  ['Msmall'] = { 0x006D },-- LATIN SMALL LETTER M
  ['Nsmall'] = { 0x006E },-- LATIN SMALL LETTER N
  ['Ntildesmall'] = { 0x00F1 },-- LATIN SMALL LETTER N WITH TILDE
  ['OEsmall'] = { 0x0153 },-- LATIN SMALL LIGATURE OE
  ['Oacutesmall'] = { 0x00F3 },-- LATIN SMALL LETTER O WITH ACUTE
  ['Ocircumflexsmall'] = { 0x00F4 },-- LATIN SMALL LETTER O WITH CIRCUMFLEX
  ['Odieresissmall'] = { 0x00F6 },-- LATIN SMALL LETTER O WITH DIAERESIS
  ['Ogoneksmall'] = { 0x02DB },-- OGONEK
  ['Ogravesmall'] = { 0x00F2 },-- LATIN SMALL LETTER O WITH GRAVE
  ['Oslashsmall'] = { 0x00F8 },-- LATIN SMALL LETTER O WITH STROKE
  ['Osmall'] = { 0x006F },-- LATIN SMALL LETTER O
  ['Otildesmall'] = { 0x00F5 },-- LATIN SMALL LETTER O WITH TILDE
  ['Psmall'] = { 0x0070 },-- LATIN SMALL LETTER P
  ['Qsmall'] = { 0x0071 },-- LATIN SMALL LETTER Q
  ['Ringsmall'] = { 0x02DA },-- RING ABOVE
  ['Rsmall'] = { 0x0072 },-- LATIN SMALL LETTER R
  ['Scaronsmall'] = { 0x0161 },-- LATIN SMALL LETTER S WITH CARON
  ['Ssmall'] = { 0x0073 },-- LATIN SMALL LETTER S
  ['Thornsmall'] = { 0x00FE },-- LATIN SMALL LETTER THORN
  ['Tildesmall'] = { 0x02DC },-- SMALL TILDE
  ['Tsmall'] = { 0x0074 },-- LATIN SMALL LETTER T
  ['Uacutesmall'] = { 0x00FA },-- LATIN SMALL LETTER U WITH ACUTE
  ['Ucircumflexsmall'] = { 0x00FB },-- LATIN SMALL LETTER U WITH CIRCUMFLEX
  ['Udieresissmall'] = { 0x00FC },-- LATIN SMALL LETTER U WITH DIAERESIS
  ['Ugravesmall'] = { 0x00F9 },-- LATIN SMALL LETTER U WITH GRAVE
  ['Usmall'] = { 0x0075 },-- LATIN SMALL LETTER U
  ['Vsmall'] = { 0x0076 },-- LATIN SMALL LETTER V
  ['Wsmall'] = { 0x0077 },-- LATIN SMALL LETTER W
  ['Xsmall'] = { 0x0078 },-- LATIN SMALL LETTER X
  ['Yacutesmall'] = { 0x00FD },-- LATIN SMALL LETTER Y WITH ACUTE
  ['Ydieresissmall'] = { 0x00FF },-- LATIN SMALL LETTER Y WITH DIAERESIS
  ['Ysmall'] = { 0x0079 },-- LATIN SMALL LETTER Y
  ['Zcaronsmall'] = { 0x017E },-- LATIN SMALL LETTER Z WITH CARON
  ['Zsmall'] = { 0x007A },-- LATIN SMALL LETTER Z
  ['afii10063'] = { 0x0433 },-- CYRILLIC SMALL LETTER GHE
  ['afii10064'] = { 0x0431 },-- CYRILLIC SMALL LETTER BE
  ['afii10192'] = { 0x0434 },-- CYRILLIC SMALL LETTER DE
  ['afii10831'] = { 0x043F },-- CYRILLIC SMALL LETTER PE
  ['afii10832'] = { 0x0442 },-- CYRILLIC SMALL LETTER TE
  ['ampersandsmall'] = { 0x0026 },-- AMPERSAND
  ['arrowhorizex'] = { 0x23AF },-- HORIZONTAL LINE EXTENSION
  ['arrowvertex'] = { 0x23D0 },-- VERTICAL LINE EXTENSION
  ['asuperior'] = { 0x0061 },-- LATIN SMALL LETTER A
  ['braceex'] = { 0x23AA },-- CURLY BRACKET EXTENSION
  ['braceleftbt'] = { 0x23A9 },-- LEFT CURLY BRACKET LOWER HOOK
  ['braceleftmid'] = { 0x23A8 },-- LEFT CURLY BRACKET MIDDLE PIECE
  ['bracelefttp'] = { 0x23A7 },-- LEFT CURLY BRACKET UPPER HOOK
  ['bracerightbt'] = { 0x23AD },-- RIGHT CURLY BRACKET LOWER HOOK
  ['bracerightmid'] = { 0x23AC },-- RIGHT CURLY BRACKET MIDDLE PIECE
  ['bracerighttp'] = { 0x23AB },-- RIGHT CURLY BRACKET UPPER HOOK
  ['bracketleftbt'] = { 0x23A3 },-- LEFT SQUARE BRACKET LOWER CORNER
  ['bracketleftex'] = { 0x23A2 },-- LEFT SQUARE BRACKET EXTENSION
  ['bracketlefttp'] = { 0x23A1 },-- LEFT SQUARE BRACKET UPPER CORNER
  ['bracketrightbt'] = { 0x23A6 },-- RIGHT SQUARE BRACKET LOWER CORNER
  ['bracketrightex'] = { 0x23A5 },-- RIGHT SQUARE BRACKET EXTENSION
  ['bracketrighttp'] = { 0x23A4 },-- RIGHT SQUARE BRACKET UPPER CORNER
  ['bsuperior'] = { 0x0062 },-- LATIN SMALL LETTER B
  ['centinferior'] = { 0x00A2 },-- CENT SIGN
  ['centoldstyle'] = { 0x00A2 },-- CENT SIGN
  ['centsuperior'] = { 0x00A2 },-- CENT SIGN
  ['commaaccent'] = { 0x0326 },-- COMBINING COMMA BELOW
  ['commainferior'] = { 0x002C },-- COMMA
  ['commasuperior'] = { 0x002C },-- COMMA
  ['copyrightsans'] = { 0x00A9 },-- COPYRIGHT SIGN
  ['copyrightserif'] = { 0x00A9 },-- COPYRIGHT SIGN
  ['cyrBreve'] = { 0x02D8 },-- BREVE
  ['cyrFlex'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['cyrbreve'] = { 0x02D8 },-- BREVE
  ['cyrflex'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['dblGrave'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['dblgrave'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['dieresisacute'] = { 0x0308, 0x0301 },-- COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['dieresisgrave'] = { 0x0308, 0x0300 },-- COMBINING DIAERESIS/COMBINING GRAVE ACCENT
  ['dollarinferior'] = { 0x0024 },-- DOLLAR SIGN
  ['dollaroldstyle'] = { 0x0024 },-- DOLLAR SIGN
  ['dollarsuperior'] = { 0x0024 },-- DOLLAR SIGN
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['dsuperior'] = { 0x0064 },-- LATIN SMALL LETTER D
  ['eightoldstyle'] = { 0x0038 },-- DIGIT EIGHT
  ['esuperior'] = { 0x0065 },-- LATIN SMALL LETTER E
  ['exclamdownsmall'] = { 0x00A1 },-- INVERTED EXCLAMATION MARK
  ['exclamsmall'] = { 0x0021 },-- EXCLAMATION MARK
  ['fiveoldstyle'] = { 0x0035 },-- DIGIT FIVE
  ['fouroldstyle'] = { 0x0034 },-- DIGIT FOUR
  ['hypheninferior'] = { 0x002D },-- HYPHEN-MINUS
  ['hyphensuperior'] = { 0x002D },-- HYPHEN-MINUS
  ['integralex'] = { 0x23AE },-- INTEGRAL EXTENSION
  ['isuperior'] = { 0x0069 },-- LATIN SMALL LETTER I
  ['lamedholamdagesh'] = { 0x05DC, 0x05B9, 0x05BC },-- HEBREW LETTER LAMED/HEBREW POINT HOLAM/HEBREW POINT DAGESH OR MAPIQ
  ['lamedholamdageshhebrew'] = { 0x05DC, 0x05B9, 0x05BC },-- HEBREW LETTER LAMED/HEBREW POINT HOLAM/HEBREW POINT DAGESH OR MAPIQ
  ['lammeemjeeminitialarabic'] = { 0xFEDF, 0xFEE4, 0xFEA0 },-- ARABIC LETTER LAM INITIAL FORM/ARABIC LETTER MEEM MEDIAL FORM/ARABIC LETTER JEEM MEDIAL FORM
  ['lammeemkhahinitialarabic'] = { 0xFEDF, 0xFEE4, 0xFEA8 },-- ARABIC LETTER LAM INITIAL FORM/ARABIC LETTER MEEM MEDIAL FORM/ARABIC LETTER KHAH MEDIAL FORM
  ['ll'] = { 0x006C, 0x006C },-- LATIN SMALL LETTER L/LATIN SMALL LETTER L
  ['lsuperior'] = { 0x006C },-- LATIN SMALL LETTER L
  ['msuperior'] = { 0x006D },-- LATIN SMALL LETTER M
  ['nineoldstyle'] = { 0x0039 },-- DIGIT NINE
  ['onefitted'] = { 0x0031 },-- DIGIT ONE
  ['oneoldstyle'] = { 0x0031 },-- DIGIT ONE
  ['osuperior'] = { 0x006F },-- LATIN SMALL LETTER O
  ['parenleftbt'] = { 0x239D },-- LEFT PARENTHESIS LOWER HOOK
  ['parenleftex'] = { 0x239C },-- LEFT PARENTHESIS EXTENSION
  ['parenlefttp'] = { 0x239B },-- LEFT PARENTHESIS UPPER HOOK
  ['parenrightbt'] = { 0x23A0 },-- RIGHT PARENTHESIS LOWER HOOK
  ['parenrightex'] = { 0x239F },-- RIGHT PARENTHESIS EXTENSION
  ['parenrighttp'] = { 0x239E },-- RIGHT PARENTHESIS UPPER HOOK
  ['periodinferior'] = { 0x002E },-- FULL STOP
  ['periodsuperior'] = { 0x002E },-- FULL STOP
  ['questiondownsmall'] = { 0x00BF },-- INVERTED QUESTION MARK
  ['questionsmall'] = { 0x003F },-- QUESTION MARK
  ['radicalex'] = { 0x23D0 },-- VERTICAL LINE EXTENSION
  ['registersans'] = { 0x00AE },-- REGISTERED SIGN
  ['registerserif'] = { 0x00AE },-- REGISTERED SIGN
  ['rehyehaleflamarabic'] = { 0x0631, 0xFEF3, 0xFE8E, 0x0644 },-- ARABIC LETTER REH/ARABIC LETTER YEH INITIAL FORM/ARABIC LETTER ALEF FINAL FORM/ARABIC LETTER LAM
  ['rsuperior'] = { 0x0072 },-- LATIN SMALL LETTER R
  ['rupiah'] = { 0x20A8 },-- RUPEE SIGN
  ['sevenoldstyle'] = { 0x0037 },-- DIGIT SEVEN
  ['sixoldstyle'] = { 0x0036 },-- DIGIT SIX
  ['ssuperior'] = { 0x0073 },-- LATIN SMALL LETTER S
  ['threeoldstyle'] = { 0x0033 },-- DIGIT THREE
  ['threequartersemdash'] = { 0x2014 },-- EM DASH
  ['trademarksans'] = { 0x2122 },-- TRADE MARK SIGN
  ['trademarkserif'] = { 0x2122 },-- TRADE MARK SIGN
  ['tsuperior'] = { 0x0074 },-- LATIN SMALL LETTER T
  ['twooldstyle'] = { 0x0032 },-- DIGIT TWO
  ['zerooldstyle'] = { 0x0030 },-- DIGIT ZERO
}
